### ISSUE TITLE
Where filter on nested objects fails

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1003]
Example:

```graphql
{
  Get{
    Things{
      Publication(where:{
        path: ["HasArticles", "Article", "wordCount"],
        operator: GreaterThan,
        valueInt: 1000
      }){
        name
        HasArticles{
          ... on Article{
            title
            wordCount
          }
        }
      }
    }
  }
}
```

Shows an empty response but should return results with a `wordCount` > 1000.

Current response:

```json
{
  "data": {
    "Get": {
      "Things": {
        "Publication": []
      }
    }
  },
  "errors": null
}
```

**Comment by etiennedi** [comment]
This is explicitly tested with an acceptance test and works on the test data set. So it must only occur on your specific data set (or some other currently unknown circumstances). 

1. Are there any errors on the logs (related to caching)? If so please post them here.
2. If not, please create a minimal (!) way to reproduce this issue.

**Comment by bobvanluijt** [comment]
It is running on the WPC.

1. I can't see them because I'm using a WPC service. Example: https://www.youtube.com/watch?v=k4ykA1L3hHI
2. It is this dataset: https://github.com/semi-technologies/DEMO-NewsPublications

**Comment by etiennedi** [comment]
1. Which cluster (id) is it? I can check the logs manually then?

(Side-Note: cc @fefi42 how do we want to deal with this in general? should we send some alerts to the WPC support team whenever a cluster logs something of criticality level `error`?)

**Comment by bobvanluijt** [comment]
Cluster is in Slack

**Comment by etiennedi** [comment]
I'm seeing a lot of timeouts when trying to build the cache in the logs. 

This could have several reasons:

1. It's a follow up issue of #1004 where due to a bug we're trying to write much more into the cache then we should.
2. The size of the dataset requires a larger setup than the minimally scaled WCS cluster. However, I'm leaning towards 1.

Needs some digging into it to completely find what's going on.

**Comment by bobvanluijt** [comment]
I also tried it locally. Same error.

**Comment by bobvanluijt** [comment]
Just noticed that the logs keep looping (related to #1004 as mentioned above)

```json
{
    "action": "esvector_cache_cycle",
    "error": "caching cycle: populate cache for thing with id eaa33b83-3927-3aaf-af4b-4990c79485da: populate weaviate://localhost/things/8fc23ebf-c645-3cc3-bd0c-891d04b601b0: populate weaviate://localhost/things/eaa33b83-3927-3aaf-af4b-4990c79485da: populate weaviate://localhost/things/07e07a0f-76c1-3131-b5a0-3152aaeb33cc: vector search: context deadline exceeded",
    "level": "error",
    "msg": "could not complete caching cycle",
    "time": "2019-10-06T15:57:34Z"
}
```

**Comment by etiennedi** [comment]
## Detailed Analysis

This issue was made of up of two cascading issues. On the on hand #1004 - which has been fixed separately. On the other hand, the demo schema mentioned above is an unusual schema - in comparison to most other schemas we've seen so far. It does not contain a large linking depth, but it is very highly interlinked (often in both directions). It is therefore a "shallow, but wide" schema in which the docs recommend to lower the default `denormalizationDepth`. Changing the value from `3` to `2` fixes this issue with caching.

As a result we have decided to lower the default denormalizationDepth to 2 as part of 0.20.2. This should still work well for most use cases and if a higher denormalization is really needed, users can always increase it.
