### ISSUE TITLE
SUGGESTION: Automatically add unknown words from objects to the C11y

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1007]
related to: #946

If a concept is added in the object, it should become part of the C11y so that somebody can explore for it.

Pseudo-concept:

```json
{
    "SomeThingOrAction": {
        "someProperty": "Hello, this is a value that should be indexed and it contains the weird concept test::334::something and the abbreviation RRKLD"
    }
}
```

Besides stop words, the word `test::334::something` will not be indexed and neither will be the concept `RRKLD`.

I have seen a use case where a user wants to be able to explore those concepts.

# Suggestion

- When an unknown word is encountered. It is added to the C11y based on the vector position of the original object.
- When a user adds it manually later via #946 this should be the leading vector definition.

**Comment by etiennedi** [comment]
In the above `test::334::something` would be split up into `"test", "334", "something"` due to the splitting rules described in https://github.com/semi-technologies/contextionary/issues/7 **both at index time and at query time**. Therefore it would probably not be recognized as an unknown word. 

With the current splitting strategy adding words with splitting characters (regardless of manually or automatically) would be without noticeable effect as a split would always occur **before** checking the synonym list. I'm not sure if changing this order would make sense as the synonym list check should occur as close to checking the actual c11y as possible. 

Regardless of the above, the proposal makes sense for `RRKLD` and I think it's a good way to easily enable additional queries.

**Comment by fefi42** [comment]
It would also make sense to provide an endpoint to list these automatically added words.

**Comment by etiennedi** [comment]
> It would also make sense to provide an endpoint to list these automatically added words.

Good point, that should make it much easier to build a custom dictionary.

**Comment by bobvanluijt** [comment]
Still relevant...
