### ISSUE TITLE
Restricting all references in where clause for gql

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate#1032]
Suppose one is allergic and searches for an apartment that has no cat:
```
{
  Get {
    Things {
      Apartment (where: {
            path: ["hasPet", "Pet", "name"]
            operator: NotEqual
            valueString: "cat"
          }
      }){
        name
        hasPet {
          ... on Pet {
            name
          } } } } } }
```

Right now this query will return all apartments that have either no Pets at all or at least one pet that is not a cat. What would be needed is a `NoneEqual` operator that does enforce that none of the references has this value.

**Comment by etiennedi** [comment]
`NoneEqual` seems like an intuitive name for this operator to me. Possibly `NoReferenceEquals` to make it even more explicit?

Thoughts @bobvanluijt @laura-ham?

**Comment by etiennedi** [comment]
Note to myself on how to implement this: Since reference props are currently already nested objects in our ES mappings, we can have an inner query to find each reference where the condition is met at least once, then an outer query with `must_not` on the inner query like so: https://discuss.elastic.co/t/elasticsearch-must-not-on-all-elements-in-array/138390/3

**Comment by bobvanluijt** [comment]
> Thoughts @bobvanluijt @laura-ham?

I leave this one to @laura-ham :-)

**Comment by laura-ham** [comment]
I'd say `NoneEqual` is most intuitive and best option for me.

**Comment by bobvanluijt** [comment]
Should this one stay open?
