### ISSUE TITLE
Removing an object that is referenced by another object results in the cache failing to refresh

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate#1034]
Currently removing an object that is still referenced by another object results in an infinite loop with errors like this:
```
{"action":"esvector_cache_cycle","error":"caching cycle: populate cache for thing with id 8d4ec4e0-9acf-550c-92de-554466386d6f: populate weaviate://localhost/things/b36268d4-a6b5-5274-985f-45f13ce0c642: thing with id 'b36268d4-a6b5-5274-985f-45f13ce0c642' not found","level":"error","msg":"could not complete caching cycle","time":"2019-11-18T10:28:48Z"}
```

Two features would be nice to handle this
- Error message if thing could not be deleted due to existing references
- Delete recursively, deleting all existing references and the thing itself

**Comment by etiennedi** [comment]
My proposal based on your two suggestions would be:

- Treat the current behavior as a bug and consider the bug fix by implemeting your first solution (i.e. prevent deletion due to existing references), prioritize it highly as the above behavior is dangerous
- Treat the "delete recursively" as a nice-to-have future feature which we can prioritize based on how frequently we'd need it

**Comment by etiennedi** [comment]
This particular bug will become obsolete with #1069. However, we probably still need something to clean up stale references which would still be saved, but can never be resolved.
