### ISSUE TITLE
weaviate without docker

### ISSUE THREAD

**Issue by ansarizafar** [semi-technologies/weaviate#1042]
Is it possible to use weaviate without docker. Do you provide a single binary to install and use weaviate

**Comment by etiennedi** [comment]
While it is technically possible to run Weaviate without docker, this means you have to run all its dependencies on your own. This means you need to run an esvector instance (currently only [distributed via Dockerhub](https://hub.docker.com/repository/docker/semitechnologies/esvector)), an [etcd cluster](https://github.com/etcd-io/etcd), and a [contextionary service](https://github.com/semi-technologies/contextionary). If you have those running (and the service discovery correctly configured in the `config.yaml`), you can you can start Weaviate without Docker. Since this is not as straight-forward as starting a docker-compose setup, we don't currently advertise this way. 

The binary is currently not distributed in isolation. However, you can 
* either extract it from the latest docker image
* or build it yourself using a golang runtime

At the moment we don't have a single-binary run to emulate everything (like `minikube` for Kuberenetes). While this is not currently on the roadmap, I wouldn't rule out that we come up with something like that in the future. Until then, the most straight-forward way to try out Weaviate is to simply install Docker and do a `docker-compose up` as [described in the docs](https://www.semi.technology/documentation/weaviate/current/getting_started.html#installation). If you are looking for a production-quality setup, we recommend spinning up a Kubernetes cluster at the Cloud provider of your choosing and simply [installing our helm chart](https://github.com/semi-technologies/weaviate-helm).
