### ISSUE TITLE
Patch (merge) does not error if second ref is set even though cardinality is atMostOne

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1051]

**Comment by fefi42** [comment]
The expected behavior with patch is that the given values are overwritten while the other values are maintained. However there is the question on how to deal with references in general. Should a patch replace all references with the new once or just append the references of the new request to the already existing thing?

There are now two ways to handle this behavior:
1. Replace all references that exist if new references are given (no matter if many or atMostOne)
This would be consistent but would miss a regularly wanted function to append new references. So I would suggest to have a parameter *appendReferences* for this option.

2. Always append *many* references and always replace *atMostOne* references. Appending references seems like a more common problem so it could be the default behavior.

I would tend more to 1 because of the coherence but it would also mean a breaking change afaik.
