### ISSUE TITLE
SUGGESTION: Dump vectors

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1073]
Some data scientists might want to leverage the vectorization mechanism in Weaviate to train new models. The result would be similar to `/things` and `/things/{UUID}` but with a focus on a matrix to download all objects.

RESTful URL suggestion: `/c11y/vectors` and `/c11y/vectors/{UUID}`.

# `c11y/vectors/{UUID}`

returns:

```js
{
    "type": "thing",
    "vector": [
        0,
        0,
        0,
        0,
        //etc
    ]
}
```

# `c11y/vectors?page=0`

returns:

```js
{
    "result": {
        "UUID_1": {
            "type": "thing",
            "vector": [ //Array is same object as c11y/vectors/{UUID}
                0,
                0,
                0,
                0,
                //etc
            ]
        },
        "UUID_1": {
            "type": "thing",
            "vectors": [ //Array is same object as c11y/vectors/{UUID}
                0,
                0,
                0,
                0,
                //etc
            ]
        }
    },
    "pages": 100 // total pages
}
```

**Comment by bobvanluijt** [comment]
thoughts: @etiennedi, @fefi42, @laura-ham ?

**Comment by fefi42** [comment]
Yes please

**Comment by etiennedi** [comment]
Some thoughts:

* The general idea of this makes a lot of sense and I'm all for it.
* The suggested pagination with numbered pages is not possible with our storage backend (Elasticsearch). A pagination like that would only work up to 10,000 elements. However, 10,000 is also the maximum for a single query, so this pagination wouldn't produce any benefits over a single large query. A possible alternative would be build something that in the background makes use of the [Scroll API of Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/search-request-body.html#request-body-search-scroll) (*Note: They write "it is not meant for real-time usage", I have yet to figure out what that actually means*)
* To be actually RESTful, I don't think we should consider `vector` to be a standalone resource. It's just a property of an existing resource: the thing and action resource. (Especially since it's described by the same uuid. Describing two different resources by the same id sounds like quite an anti-pattern to me.) So, a more REST-compliant URI would in my opinion be something like `GET /v1/things/{uuid}/vector` and/or `GET /v1/things/{uuid}?includeVector=true`, similarly for the list on `GET /v1/things?includeVector=true` (Possibly also a different parameter to show only the vector). 

  The major advantage of this would also be that if we build a "page-through-everything-export" API it wouldn't be limited to just vectors, but could be used to dump all the data.

**Comment by fefi42** [comment]
@etiennedi I agree with the RESTful objection.

This is a duplicate #1041 btw.

**Comment by bobvanluijt** [comment]
> * The major advantage of this would also be that if we build a "page-through-everything-export" API it wouldn't be limited to just vectors, but could be used to dump all the data.

Agreed, let's not forget though, that the use case is a matrix that the end-user can easily obtain. I.e. `[UUID, vector1, vector2, etc]`

> The suggested pagination with numbered pages is not possible with our storage backend.

I see, it defeats the purpose if this is not possible though... It would be interesting to understand the possibilities.

**Comment by fefi42** [comment]
Do we need an endpoint for loading the matrix?
We could document how to create a query in which you can request all the vectors up to 10,000 items. 
One could query even more if they can limit the data somehow e.g. only things in a region or something.
I think for the moment this is enough. Once we actually get an request for more we can think of something new.

We could also create a client function that abstracts this away from the user. Then at least python users would be able to receive the vectors in a matrix like structure like a numpy array. Which is compatible with almost all ML libs.

**Comment by etiennedi** [comment]
> Agreed, let's not forget though, that the use case is a matrix that the end-user can easily obtain. I.e. [UUID, vector1, vector2, etc]

I don't think this is any more or less possible with one or the other approach. Or am I missing anything?

 > I see, it defeats the purpose if this is not possible though... It would be interesting to understand the possibilities.

A pagination using **numbered pages** is not possible (beyond 10,000 items). However, as mentioned there are alternatives, such as scrolling. So the overall goal of "getting all objects/vectors out" is still possible. However, it won't be possible to access page 7 out of 12000 out of the blue. But I also don't think that matters, since this API would probably either be used for a full export or nothing.

> I think for the moment this is enough. Once we actually get an request for more we can think of something new.

This would at least be a good suggestion to make the tasks a bit smaller:
1. Enable getting "all" (up to 10,000) objects/vectors
2. Enable scrolling or similar means to get all (unlimited) objects/vectors

> We could also create a client function that abstracts this away from the user. Then at least python users would be able to receive the vectors in a matrix like structure like a numpy array.

Fully agreed, I don't think we should give up structure in our API, simply because a subset of users need something less structured. It's always easy to remove structure client-side, so converting a simple `{"uuid": "123", "vector": []}` object into a "row" in the matrix is something we could support in the client.

**Comment by bobvanluijt** [comment]
> Do we need an endpoint for loading the matrix?

@fefi42 not sure I understand, do you mean _down_ loading?

> Or am I missing anything?

@etiennedi nope, more that it would defeat the purpose if people can't get the whole thing out. If that's with pagination or not is for me trivial. It was a suggestion :-)

**Comment by bobvanluijt** [comment]
Additionally, can we also have a flag or so to include or exclude individual words from the results?

**Comment by etiennedi** [comment]
@bobvanluijt can you provide an example of what it would mean to
> include or exclude individual words from the results?

**Comment by bobvanluijt** [comment]
> can you provide an example of what it would mean[.]

Yes, I would now expect the behavior to include both individual words _and_ things and actions. It would be nice to have a flag to _only_ show words or _only_ show things and actions.

**Comment by etiennedi** [comment]
Outscoped the "include objects in response" to #1095 so we can work on this independently

**Comment by qingwei91** [comment]
Hi, is this still being considered?

I have an analytic use case that will benefit from ability to bulk export data or scan data

**Comment by bobvanluijt** [comment]
> Hi, is this still being considered?

Good question @qingwei91 – for a full dump we need @etiennedi's feedback. That said, you can use the [offset filter (pagination) filter](https://www.semi.technology/developers/weaviate/current/graphql-references/filters.html#offset-filter-pagination) to get all the vectors back

**Comment by qingwei91** [comment]
Hi @bobvanluijt thank you, I didnt realize pagination is supported, that will do for me

**Comment by bobvanluijt** [comment]
> Hi @bobvanluijt thank you, I didnt realize pagination is supported, that will do for me

Awesome!
