### ISSUE TITLE
Weaviate 0.22.3 displays the wrong version

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1102]
Running 0.22.4 results in displaying:

```js
{
contextionaryVersion: "en0.10.0-v0.4.7",
contextionaryWordCount: 677763,
hostname: "http://[::]:8080",
version: "0.22.3" <== WHOOPS
}
```

On the meta endpoint

**Comment by etiennedi** [comment]
Thanks for finding this. This means something in the build process must have gone wrong, as this is never set manually. I'll investigate.

**Comment by etiennedi** [comment]
Found the problem, the tag is on the commit that updates the swagger.json, but the `generate_code_from_swagger` hadn't run yet at that point, so that's only in the next commit. But Weaviate was already published at that point.

![image](https://user-images.githubusercontent.com/8974479/76738087-40d33800-676a-11ea-999f-578d1f8b3bcd.png)

I'll republish which should fix this. Note that this is only a cosmetic issue, all changes are contained in the latest release.

**Comment by etiennedi** [comment]
[Build is triggered](https://travis-ci.org/github/semi-technologies/weaviate/builds/662971791?utm_source=github_status&utm_medium=notification). The issue should be fixed when the built is through, keeping open until then.

**Comment by bobvanluijt** [comment]
Cool, it was a bit confusing for me 😆

**Comment by etiennedi** [comment]
Fixed after re-release

```
curl -s localhost:8080/v1/meta | jq
{
  "contextionaryVersion": "en0.10.0-v0.4.7",
  "contextionaryWordCount": 677763,
  "hostname": "http://[::]:8080",
  "version": "0.22.4"
}
```
