### ISSUE TITLE
Keep data available for restart using docker compose

### ISSUE THREAD

**Issue by jettro** [semi-technologies/weaviate#1120]
If I have a smooth running weaviate with components and data, but it is time to start doing something else. I want to stop the complete solution "docker-compose down", but I want to keep the data. If I want to continue, do a docker-compose up -d and ready to go. 

At the moment I have to start over, I do keep the elasticsearch node by adding these lines to the config, but that only helps in getting my docker runtime image (on the mac) smaller.
```
    volumes:
      - ./elastic/data:/usr/share/elasticsearch/data    
```

**Comment by etiennedi** [comment]
I agree that we should make this possible, but I think it should not be the default for the following reasons:

* It's common that docker containers don't have persistent volumes. E.g. if I want to spin up a `mysql` db in docker (using `docker run -p xx:yy mysql`) all state will be gone after I delete the container. Weaviate can't be run from a single container which is why we need the docker-compose. Nevertheless the expectation should be the same in my opinion: If you don't change anything, nothing is persisted.

* We position the docker-compose setup as a try-out setup, so if a run doesn't lead to the desired results, the easiset way to start from scratch is a `docker-compose down && docker-compose up`. If volumes are persisted the user will actively have to delete the volumes to get a clean start. While certainly possible it requires a bit more understanding of docker. From my understanding the "start again and have a clean slate" is used commonly when developing solutions around Weaviate locally (cc @michaverhagen @fefi42)?

* We want to encourage users to see the K8s setup as the production setup and the docker-compose as the tryout setup. The main reason behind that is that docker-compose doesn't bring the same self-healing and scaling capabilites as Kubernetes. So if a user starts to run a docker-compose setup in production and then realize they're locked into specific config or it doesn't run as stable this might reflect badly on Weaviate. Running without persistence by default is another indicator to make more clear that this is a dev/tryout setup and not a production setup. In my opinion this is the weakest argument out of the three, but nevertheless carries some weight.

cc @bobvanluijt

**Comment by fefi42** [comment]
Yes I can confirm that I regularly reset my local deployments just by restarting the docker-compose. I also agree that the feature should be available (as none default option).
