### ISSUE TITLE
Why is the Weaviate NPM package deprecated?

### ISSUE THREAD

**Issue by kenaitian** [semi-technologies/weaviate#1154]
https://www.npmjs.com/package/weaviate

**Comment by bobvanluijt** [comment]
Hi @kenaitian, 

Well spotted ;-)

This is because it was related to a -very- old version of Weaviate. We are working on releasing a new one in the near future (similar to the [Python package](https://www.semi.technology/documentation/weaviate/current/client-libs/python.html)). If you want to, you can leave your email [here](https://www.semi.technology/newsletter/) and we will email when the package is available.

For now, you can use the GraphQL package to connect directly to Weaviate.

I will also keep this issue open and mention it here when we have a new NPM client available.
