### ISSUE TITLE
Allow adding references even if they don't (yet) exist

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1163]
Currently, a developer needs to import a graph like this:

1. Add objects without references.
2. Add other objects with references to objects from bullet 1.
3. Update references in bullet 1.
4. etc...

Because we often create custom UUIDs, it would be helpful if a user can set a reference _even if it doesn't exist yet_.

This would make the flow easier, people can not only add references without needing to check if they are already in Weaviate, they can also add objects simultaneously speeding up the import process.

I would propose a simple flag to do this:

```
POST /v1/{semanticKind}?validateReferences=false
```

PS:
Ideally, this should work for all endpoints where references play a role, for example batching.

PPS:
CC: @michaverhagen @fefi42 @laura-ham

**Comment by rahmatnazali** [comment]
Hi!
Since I'm using weaviate python client, does this feature already implemented there?

Currently my case is I must have `time.sleep(2)` to be executed between `create_thing` and `add_reference_to_thing` to be able to link between objects.

Let me know if I missed something.

**Comment by fefi42** [comment]
@rahmatnazali weaviate needs up to 2 seconds to update its index. The client currently has no feature that prevents this error. You can create an issue in the client project https://github.com/semi-technologies/weaviate-python-client

To handle this at the moment you have two options:
1. Use a loading pattern where you first load all things and then load all references. Have a 2 second pause in between.
2. Use the batching API. In the batching API some validations are surpassed to speed up the loading. Checking if a thing really exists is one of them. This solves this error message however for now you have to be sure that the things you reference really exist, since broken references might lead to an inconsistent state and broken queries. We are also in the process to change that.
