### ISSUE TITLE
Classification fail because all shard are failed

### ISSUE THREAD

**Issue by syahdeini** [semi-technologies/weaviate#1222]
When I try to classify data using sourceWhere, 
```
"class": "Comments",
            "classifyProperties": ["ds_standard"],
            "basedOnProperties": ["desc"],
            "type": "contextual",
                "sourceWhere": {"path": ["isAnimal", "Animal", "IsMadeBy", "God", "WorkIn", "Dimension", "description"], "operator":"Equal", "valueString": "Cat"}	
            }
```
The result : 
`'error': 'classification failed: vector search: request is error: status: 400 Bad Request, type: search_phase_execution_exception, reason: all shards failed, shards: too_many_clauses: maxClauseCount is set to 1024', 'id'`

**Comment by etiennedi** [comment]
Hi @syahdeini 

The issue in your `sourceWhere` filter related to the path length. Your path
`["isAnimal", "Animal", "IsMadeBy", "God", "WorkIn", "Dimension", "description"]`
makes three hops (`Comments->Animal`, `Animal->God`, `God->Dimension`). The amount of hops is not a problem per se, but it can become a problem depending on the dataset complexity.

Internally what happens on such a query is this.

1. We make a lookup where the innermost filter of the path is matched, i.e. `Dimension.description == "Cat"`. This returns a list of matching IDs
2. We make the next lookup for `God.workIn` where condition is "at least one of the IDs returned in 1 are contained"
3. We make the next lookup for `Animal.isMadeBy` where the condition is "at least one of the IDs returned in 2 are contained"
4. We make the outermost lookup for `Comments.isAnimal` where the condition is "at least one of the IDs returned in 3 are contained"

Somewhere in between Step 2 and 4 the list of "possibly matching IDs" returned from the previous query exceeds 1024 which causes Elasticsearch to throw the error seen above. While this setting can in theory be increased, the root cause is something else: Your filter touches upon a large portion of the dataset, that is larger than what can be computed in a single request. Such a long and deeply nested filter can work, but only if it is very restricted on anything but the **outermost layer**. For example, let's say the amount of items matching would be something like:

1. `Dimension.description == cat` -> matches 20 items
2. `God.WorkIn == Dimensions returned in 1` matches 5 items
3. `Animal.IsMadeBy == Gods returned in 2` matches 20 items
4. `Comments.isAnimal == Animals returned in 3` matches 9000 items

Note that the last step returned a lot of items. This wouldn't be an issue. But if any of the previous step find more than 1024 items, the filter chain breaks.

### How to proceed from here?

I think there are two possible alternatives to fix this issue:

1. Use a more restrictive path. As outlined above if a path should be this deeply nested it needs to be very restrictive in the middle. (Based on the above I cannot tell which part of your chain is very unrestricted. But what you can do is use a regular `Get()` request where you set a where filter starting with the innermost part of the path (e.g. `Dimension.description == "cat"`) and see how many results are returned. If it's below 1024, iterate over your results and run the next query (e.g. `God.WorkIn.Dimension.id == id`). If the unique sum of all results is more than 1024 you know where the problem lies. If not, continue with the next layer.
2. Denomarlize parts of our query. For example, add a primtive prop to your `Comments` class that makes for a simpler filter. E.g. a filter like `Comments.someBoolProp == true` can be very efficiently looked up and will not lead to those recursive limitations.

### Can this be "fixed" in Weaviate?
There are two parts to this issues:
1. The 1024 limit is a symptom. This could be worked around - for example - by running queries sequentially to stay within limits.
2. A deeply nested **and** unrestrictive filter query always has the potential to touch the entire dataset. Depending on dataset size, this can easily become too much to handle on a single request. In this case the dataset design needs to be improved to allow for more efficient lookups (e.g. through fewer hops)
