### ISSUE TITLE
Spike/POC Improve moveAwayFrom formula

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1267]
The current moveAwayFrom formula in explore searches has unintuitive results. If the force is high enough and the moveAwayFrom vector is close to the original source, we end up at a very different end of the vector space where we seemingly lose all meaning.

The improvement idea is instead to just move by the delta instead of by the whole vector. This is unproven as of now and needs Spiking/Investigation to find out if this actually improves results.

**Comment by laura-ham** [comment]
**The identified problem:** 
In the calculation of the search vector with the `moveAwayFrom` argument, the following happens. The vector of the `moveAwayFrom` concepts is taken and mirrored against the origin of the vector space. This point is then taken in a similar calculation as `moveTo`, with the idea that you want to 'move to' the opposite of the `moveAwayFrom` vector. 

In essence this idea is right, but implemented wrong. You indeed want to 'move to' the opposite of the `moveAwayFrom` vector, but the "opposite" of this vector is calculated wrong, namely against the origin instead of the current search vector you want to apply the move away function on.

**Proposed solution:**
Handle a `moveAwayFrom` argument as follows:
1. Calculate the vector position of the `moveAwayFrom` concepts (already done correctly)
2. Calculate the vector position of the  `moveAwayFrom` concepts as **opposite of the source vector** (instead of as opposite of the vector space origin). Could be like: `opposite_of_moveawayfrom_vector = ( 2 * source_vector ) - moveawayfrom_vector`

3. Calculate the new vector position of the search query similar as `moveTo`, because in essence you want to move to the vector resulted from step 2. With the formula as already known: 

`source_vector * ( 1 - moveawayfrom_force * multiplier ) + direction * opposite_of_moveawayfrom_vector * ( moveawayfrom_force * multiplier )`

, where `direction` is always 1 so could be left out.

**Comment by laura-ham** [comment]
> Question: What's the motivation behind the `2 *` in `2 * source_vector` ? Based on the WhatsApp video (1 of 3) I would have assumed that we simply need `source_vector - move_away_vector`?

That's to apply the delta to the source vector. So `source_vector - move_away_vector` calculates the delta (aka difference between the source and move_away_vector, aka the lowest dotted line in the picture). And to get to the `opposite_of_moveawayfrom_vector` (aka the `x` in the lower graph of the picture), we need to apply the delta to the `source_vector`. 

So `2 * source_vector` simply comes from `(source_vector - move_away_vector) + source_vector`

**Comment by etiennedi** [comment]
But isn't this taken care of by the left half of the final formula already?

Given the following numbers and ignoring weighing for the sake of simplicity:

```
source: (1.0, 1.0)
moveAwayFrom (1.2, 0.8)
```

Igonring the `2x` the final formula would be

```
vec = source + (source-moveAwayFrom)
    = (1.0, 1.0) + (-0.2, 0.2)
    = (0.8, 1.2)
```

which matches the number from you WhatsApp video (and also makes sense intuitively), but I completely ignored the `2*`?

**Comment by laura-ham** [comment]
Yes, 
```
vec = source + (source-moveAwayFrom)
    = (1.0, 1.0) + (-0.2, 0.2)
    = (0.8, 1.2)
```

would be the calculation to calculate the vector that the source vector needs to **move towards**.   So that's step 2. Then in step 3 you apply this vector (as `opposite_of_moveawayfrom_vector` aka `moveTo_vector`).

**Comment by etiennedi** [comment]
> vector that the source vector needs to move towards

What do we gain from from this two-step approach? Why can't it be the final target already?

**Comment by laura-ham** [comment]
The two-step approach was to clarify how the moving works, as it seemed more intuitive to explain it this way. But the shorter formula to calculate the new vector with `moveAwayFromVector` a `sourceVector` is indeed:
`finalVector = sourceVector +  moveAwayFromForce * multiplier * (sourceVector-moveAwayFromVector)`

**Comment by etiennedi** [comment]
The proposed change has been implemented and a preview docker image is available at `semitechnologies/weaviate:improved-moveaway-preview`.

Please evaluate, if it behaves as intended. If we're happy with it, I can make a release containing this as well as the #995 implementation.

**Comment by etiennedi** [comment]
New preview `semitechnologies/weaviate:improved-moveaway-preview-2` now available which makes sure that forces in either direction are fair, i.e. a force of e.g. `0.7` leads to the same movement absolute movement (in euclidean terms) whether it's on a moveTo or moveAwayFrom. Note: This does not always translate to a different cosine distance. (E.g. if me move from `(1.0, 1.0)` to `(1.1, 1.1)` the angular distance would not be changed)
