### ISSUE TITLE
SUGGESTION: introduce a hidden dataType

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1307]
A `hidden` field would work like `string` or `text` so it can be used for vectorizing data (or any other preprocessing module function), it will not be stored after vectorizing. This is ideal for searching through classified or sensitive documents. When querying, one can not collect the original data because it was not stored at all.

Explained based on an example:

```js
{
    "things": {
        "classes": [
            {
                "class": "Email",
                "description": "An email",
                "properties": [
                    {
                        "dataType": [
                            "Address"
                        ],
                        "description": "From email address",
                        "name": "from"
                    },
                    {
                        "dataType": [
                            "Address"
                        ],
                        "description": "To email address",
                        "name": "to"
                    },
                    {
                        "dataType": [
                            "hidden" // <== PROPOSED FIELD
                        ],
                        "description": "Body of the email",
                        "name": "body",
                        "vectorizeClassName": false,
                        "index": true  // <== IT CAN BE USED FOR INDEXING
                    }
                ]
            }
        ]
    }
}
```

**Comment by bobvanluijt** [comment]
A new use case for this: if one only wants to store the vectors of a document and some related meta-data (the actual original document is stored somewhere else)

**Comment by etiennedi** [comment]
I think this would also come in handy for an `img2vec` module. Images can be huge and in production it's usually smart to serve them from blob storage or a CDN, so there's not need to necessarily store them in weaviate. However, if the `img2vec` module should vectorize it, the user still has to provide it.

In this case the motivation is not "hiding" it, but rather only saving resources, so I think we could/should come up with a more generic name, but essentially it would be exactly the same feature.

I also think it wouldn't have to be its own type, but it could rather be a flag similar to `indexInverted`, because I don't think this is specific to only `text/string`, but might also work for a potential `blob` type, etc.
