### ISSUE TITLE
Support for RDF triples/SPARQL query?

### ISSUE THREAD

**Issue by namedgraph** [semi-technologies/weaviate#1522]
I am wondering how Weaviate could be used as a SPARQL service. Querying the vector space seems like an interesting idea.
To take countries/capitals as an example
```sparql
SELECT ?country
{
    <France> ?property <Paris> .
    ?country ?property <Berlin> .
}
```
should return a result `(?country, <Germany>)`. Vectors act like properties, resources as points. But that's just my imagination :)

Some related work:
* [RDF2vec](http://rdf2vec.org/)
* [Vec2SPARQL](https://www.biorxiv.org/content/10.1101/463778v1)

**Comment by bobvanluijt** [comment]
Thanks @namedgraph – I'm going to create a separate "idea" issue for RDF2Vec because there might be an opportunity as well.

I _think_ that the class property structure Weaviate uses can be expressed as RDF-triples (not 100% sure). This would allow you to go: `RDF -> Weaviate RESTful API for schema and data import -> Weaviate querying via GraphQL -> RDF`

**Comment by bobvanluijt** [comment]
Somewhat related: #1529

**Comment by bobvanluijt** [comment]
🤖 👋  --- 🧇
