### ISSUE TITLE
Show query time as _additional feature

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1554]
I think the title says it all functionality wise :-)

But I was thinking of something like:

```graphql
{
  Get {
    Article {
      _additional {
        queryTime # maybe a milliseconds timestamp or so?
      }
    }
  }
}
```

**Comment by etiennedi** [comment]
I like the idea, but I don't think `_additional{}` would be a good fit, because we can't compute the query time per object, only the overall time. But `_additional {}` is object-specific. So I think this should go in those "extra" GraphQL metadata fields (next to `"data"`) which @laura-ham disovered some time ago.

**Comment by bobvanluijt** [comment]
Perfect - as long as we know it I’m happy 😊😊😊

**Comment by bobvanluijt** [comment]
burp 🤖
