### ISSUE TITLE
Hosting on AWS services?

### ISSUE THREAD

**Issue by weisisheng** [semi-technologies/weaviate#1556]
Just discovered Weaviate and most of my noob / lower intermediate work the last year has been on AWS serverless (lambda, ddb, s3).  Are there any trailheads for working with Docker containers and hosting on AWS ECS/ECR?  Working on an MVP and I don't have the bandwidth to study/incorporate kubernetes.

Thanks in advance.

**Comment by laura-ham** [comment]
Hi @weisisheng  – that's a great question. One request though, you would do us a huge favor by asking it on [StackOverflow](https://stackoverflow.com/questions/tagged/weaviate) so that other with the same question might more easily find the answer. If thats not possible, no worries and I’ll answer it here :)

**Comment by weisisheng** [comment]
I will definitely switch it over  in the next 48 hours.  Best, V.
