### ISSUE TITLE
Allow contextual classification for transformers module

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1603]
It would be great if [this](https://www.semi.technology/developers/weaviate/current/modules/text2vec-contextionary.html#contextual-classification) function is also supported in [this](https://www.semi.technology/developers/weaviate/current/modules/text2vec-transformers.html) module (`text2vec-transformers`).

**Comment by etiennedi** [comment]
The exact `text2vec-contextionary-contextual` type is completely specific to the `contextionary` "system", i.e. it uses occurrences to calculate a classification-specific vector on the fly, etc. This was introduced after initial disappointing results with just using the existing objects vectors.

Since we don't have those means (occurrence, influence over the vector building process, etc.) available in other modules, I think we could implement a generic type `contextual` which is not specific to any module and therefore works with any module, including the `text2vec-transformers` module. It would simply pick the closest target vector for each source vector - as was the original intention.

**Comment by bobvanluijt** [comment]
That would be great!

**Comment by etiennedi** [comment]
Sure. Priority-wise, do you think this will be needed before/more urgent than the Auto-Schema feature? Or should I plan it after?

**Comment by bobvanluijt** [comment]
Also note: https://dsmaxpool.slack.com/archives/CCLK5F3NX/p1624699504272400 and related https://discuss.huggingface.co/t/new-pipeline-for-zero-shot-text-classification/681

**Comment by etiennedi** [comment]
Makes we wonder if we should name the classification `zeroshot`, that's something people already understand whereas `contextual` is something we'd need to explain to them.

**Comment by bobvanluijt** [comment]
Ha - good point

**Comment by bobvanluijt** [comment]
@laura-ham – can you please weigh in regarding the naming question?

**Comment by laura-ham** [comment]
I'm voting for `zero-shot-classification`, because people know this name, like @etiennedi mentions. I think we should stick as much as possible to familiar and official terms as possible. Zero-shot classification is exactly what it is, see also https://en.wikipedia.org/wiki/Zero-shot_learning.

We could also reuse this term for a potential zero-shot question answering module :) https://www.arxiv-vanity.com/papers/1611.05546/ and https://www.aclweb.org/anthology/2020.emnlp-main.11/

**Comment by bobvanluijt** [comment]
Thanks @laura-ham – is this _only_ a documentation and RESTful thing or does it also have an impact on the code @etiennedi ?

**Comment by etiennedi** [comment]
The naming? It's going to have some very, very minimal impact, yes. Mainly on object/function naming.

**Comment by bobvanluijt** [comment]
> The naming?

Yes :-)

> It's going to have some very, very minimal impact, yes.

@laura-ham – can you please add this to the OPS list?

**Comment by etiennedi** [comment]
cc @antas-marcin, Note that the new classification type will be called `zeroshot` (formerly planned as `contextual`). This will only affect the type we are newly adding, not the existing `text2vec-contextionary-contextual` for now. But we can think about deprecating that name as well and introducing `text2vec-contextionary-zeroshot` in a non-breaking fashion, i.e. allow both, but print a warning on the deprecated name.

**Comment by laura-ham** [comment]
> @laura-ham – can you please add this (the naming) to the OPS list?

@bobvanluijt What is the current to-do related to this? I don't see any task until changes in Weaviate are applied(new classification type or renaming `text2vec-contextionary-contextual`.

**Comment by bobvanluijt** [comment]
> I don't see any task until changes in Weaviate are applied

Certainly, but you can already create the OPS ticket with the disclaimer that this can be done when it's implemented in Weaviate ;-)
