### ISSUE TITLE
IDEA: spelling checker module

### ISSUE THREAD

**Issue by laura-ham** [semi-technologies/weaviate#1606]
This is a proposal for a spelling (and potentially grammer) checker module. There are for example some Transformer spelling and grammer modules available on Huggingface (didn't verify the accuracy etc). e.g. [this](https://huggingface.co/murali1996/bert-base-cased-spell-correction).

Some ideas on the module characteristics:
1. The module can be used for the `concepts` in the `nearText` filter, and for `question` in the `ask` filter. So the module can only be used in combination with a module that enables free text in a filter (at the moment the `nearText` or `ask` filter).
2. The `spellCheck` filter should have at least an option to enable/disable checking, and an option to force an autocorrection.
3. The result will appear in an `_additional` GraphQL field.

Design decisions to make:
1. Where to place the `spellChecker` filter: inside the `nearText` (or `ask`) argument, or outside. Now I placed it outside the `nearText` filter. I'm not sure if placing it in a filter can be achieved architecture/design wise because it means that the filter that is enabled by a module will be extended by this spelling checker module. Placing this new filter outside the `nearText` filter makes sense imo, because it can apply not only to `nearText`, but also to `ask` and potentially other text filters in the future.

Important questions for this design: 
1. This designs assumes that there is at most one filter which contains text. Currently, for example, the `ask` and `nearText` filter cannot be used simultaneously. Would there be a potential case in the future that two text-containing filters could be used in one query?
2. I didn't consider any `certainty` levels. If models output a `certainty` per checked text, then we could also enable a `minimalCertainty` the spelling checker filter. When the model is above this value, then force the autocorrection, and below not.

Proposed GraphQL design, example:
```graphql
{ 
    Get (
        nearText: {
            concepts: ["Whta did the monkye do?", "Elon Musk"]
        }
        spellCheck: {
            check: True,
            forceAutocorrect: True
        }
    ) {
        Document {
            title
            _additional {
                spellCheck: {
                    didYouMean          # or a more normal name like `correctText`
                    numberOfCorrections
                    changes {
                        original
                        didYouMean
                    }
                }
            }
        }
    }
}
```

```json
{
    "data": {
        "Get": {
            "Document": [
                {
                    "title": "...",
                    "_additional": {
                        "spellCheck": {
                            "didYouMean": ["What did the monkey do?", "Elon Musk"],
                            "numberOfCorrections": 2,
                            "changes": [{
                                "original": "Whta",
                                "didYouMean": "What" 
                            }, {
                                "original": "monkye",
                                "didYouMean": "monkey" 
                            }]
                        }
                    }
                }
            ]
        }
    }
}
```

Moreover, we could also use this spelling checker module to check unstructured text data on import time. For example: configure per class and property the data schema 
   1. Whether to use spelling checker and force an autocorrection
   2. Looking far ahead: Perhaps in the clients, build a kind of human-in-the-loop process that stops the import if a spelling/grammar mistake is found, and ask the human (in the command line), to correct this or not. Kind of how you do a spelling check in Word, where you accept or reject a change.

What do you think about 
1. The placement of the filter and result in GraphQL 
2. The chosen field words (`didYouMean` is perhaps too informal, curious to your opinion)
3. Is this achievable architectural/back-end wise?

@etiennedi @bobvanluijt

**Comment by etiennedi** [comment]
@laura-ham Could you please define a problem statement of what this is trying to solve? It is hard for me form on opinion on the proposed solution without understanding what it tries to solve. Thanks.

**Comment by laura-ham** [comment]
@etiennedi Of course. I believe the scenario that this feature can solve is the following. If a user is performing a semantic search, but made a typo in the `nearText` filter, perhaps an answer cannot be found because one or more important words with a typo can't be found in the semantic index. This can potentially be solved directly by 
1. Weaviate suggesting a search with correct spelling (like Google Search does) and/or
2. Autocorrect the query so that results are shown based on the corrected query.
This improves the general UX of a search platform imo.

@bobvanluijt can you help? You may have more context to add here.

**Comment by etiennedi** [comment]
Thanks for elaborating, I have some comments on the module architecture parts and also some questions:

## Architecture
Let me start with the modules. At the moment a module owns an entire `near<Foo>` part in the API and Weaviate itself doesn't know much about it. The contract between module and Weaviate is that Weaviate must end up with a vector and is agnostic where that vector came from. 

This means if we had a new `spellCheck` alongside `near<Foo>` this would introduce two problems: 1.) `spellCheck` alone cannot fulfill the input-to-vector contract alone and 2.) even if it could, Weaviate would now have two vectors from two modules and wouldn't know what to do with it.

So, from the above, I would say that the existing modules definitely need to be aware of this spellchecking feature and "co-operate" with it. This makes me think that it would be better if the spellcheck options would be within `ask` and within `nearText`. 

Basically I think of it this way:
* ENABLE_MODULES=`text2vec-contextionary,spellchecker` will tell weaviate that a `spellchecker` module is present, but the module itself is headless, it's only APIs would be internal. This could be similar to how `qna-` depends on a `t2v-` model internally.
* Whenever the `spellchecker` module is active and loaded, each `text2vec-*` module can decide what it wants to do with it. E.g. it could offer a `nearText.spellcheck.enabled: bool` and `nearText.spellcheck.forceAutoCorrect:bool` field. It is therefore in the responsibility of the module to call the spellchecker API. (Respectively for qna)
* This would also allow us to make a "should spell-checking be included" decision on a per module basis. For example, in `img2vec` we probably wouldn't need it, but if we had a `textnimg2vec` model in the future it might decide to make use of that, etc.
* The downside is that we have to implement the spell-check functionality and API in each module, but I think that's a very small price to pay for a clean seperation.

## API
* Based on ⬆️ , I'm for integrating `spellCheck` into `near<Foo>`
* As for the return values: It would be good to see what such a model actually returns to see what would make sense to return and how. I think we could solve the issue of spell-checking multiple inputs (if we ever need to) by making `_additional.spellcheck` an array instead of a single object. And then each object could have a field `location` which could contain something like `nearText.concepts[1]` or something like that.

## General Viability and Questions.

* Overall, I think this is something that would definitely benefit from a POC outside of Weaviate. To test how the spell-check models perform and to see how much value is actually added. To be honest, I'm also not 100% convinced that having this in Weaviate adds values. Anything that can be done with this inside Weaviate could also be done at the application level (frontend or glue code) while giving the user maximum control over the spellchecking process and giving them full power over the results, etc. Especially as this is quite far from Weaviate's core capabilities (the only real overlap in my opinion is that it would use an ML model to do the checking), I'm a bit torn if this is really added value or feature bloat.
* In line with ⬆️ it might make sense to validate if users in general perceive this as value added or if this just caters to one extremely specific case.
* One thing that might be tricky is the quality of the spell check model and that of the `t2v-model`. What if the `t2v` model is very capable of understanding a domain-specific word, but the spell-checker is not and "corrects" it? etc. Or in general if the vocabulary simply isn't in sync.
* Similar to ⬆️ `t2v` can be multi-lingual are there matching spellchecking models?

**Comment by bobvanluijt** [comment]
My $0.02.

> To be honest, I'm also not 100% convinced that having this in Weaviate adds values.

I have to disagree, I think that the fact that this comes out of the box might tremendously help in certain use cases.

> This means if we had a new spellCheck alongside near<Foo> this would introduce two problems

I appreciate the problem this introduces. Having that said I could imagine that we have future cases where we want modules to interact with the input variable.

> @bobvanluijt can you help? You may have more context to add here.

Not really, I agree with your points @laura-ham

**Comment by etiennedi** [comment]
> I appreciate the problem this introduces. Having that said I could imagine that we have future cases where we want modules to interact with the input variable.
> 
> >

In this particular case I'd argue that within the `near<Foo>` object also leads to the better UX, because the setting is closer to what it controls. If it's at root level the user wouldn't know that it affects `nearText`, but not `where`. Or maybe we want it to be able to affect `where` filters as well, then it would be cleaner if each can be configured separately. (Because maybe a filter is an ID and should not be checked, but `nearText` should, etc.).

So in my opinion the UX aspect and the Module API system are aligned on this.

**Comment by bobvanluijt** [comment]
Awesome

**Comment by laura-ham** [comment]
@etiennedi thanks for your elaborate comment and ideas!
Given the info about the architecture of modules & Weaviate, I totally agree with placing the Spelling checker inside the Text filters, as you propose. GraphQL wise, a query will look like this then (I removed `changes` in the `_additional` field, because the result will be an array of checked items):

```graphql
{ 
    Get (
        nearText: {
            concepts: ["Whta did the monkye do?", "Elon Musk"]
            spellCheck: {
                check: True,
                forceAutocorrect: True
            }
        }
    ) {
        Document {
            title
            _additional {
                spellCheck: {
                    originalText
                    didYouMean          # or a more normal name like `correctText`
                    corrected               # boolean - whether an autocorrect was applied
                    location                 # e.g. "nearText.concepts[1]"
                    numberOfCorrections
                    changes {
                        original
                        didYouMean
                    }
                }
            }
        }
    }
}
```

```json
{
    "data": {
        "Get": {
            "Document": [
                {
                    "title": "...",
                    "_additional": {
                        "spellCheck": [{
                            "originalText": "Whta did the monkye do?",
                            "didYouMean": "What did the monkey do?",
                            "numberOfCorrections": 2,
                            "changes": [{
                                "original": "Whta",
                                "didYouMean": "What" 
                            }, {
                                "original": "monkye",
                                "didYouMean": "monkey" 
                            }],
                            "location": "nearText.concepts[0]"
                        }]
                    }
                }
            ]
        }
    }
}
```

**Comment by etiennedi** [comment]
Looks good!

I just realized I didn't comment on the naming of `didYouMean` yet. I kinda like it, it's very straight-forward and everyone should understand what it means. So in `spellCheck.didYouMean` I think this is perfect. Looking at `changes[].didYouMean`, I'm wondering if maybe `.corrected` would be better here, since it would also be more inline with `numberOfCorrections` (as opposed to `numberOfDidYouMeans`). So I think I'm in favor of calling the overall thing (at `spellCheck.didYouMean` `didYouMean`, but call the individual changes `changes[]corrected`. What do you think?

Planning wise (cc @bobvanluijt) should we move this to POC stage? I.e. build a POC outside of Weaviate to see what models we need to use, what the models actually return, if that reflects our architecture etc? That should also decouple using this feature from the timeline of building the actual module. I.e. if we need this internally at point X, we can use the POC until the module is complete at point Y.

**Comment by bobvanluijt** [comment]
> Planning wise should we move this to POC stage? 

Yes please

**Comment by laura-ham** [comment]
> So I think I'm in favor of calling the overall thing (at spellCheck.didYouMean didYouMean, but call the individual changes changes[]corrected. What do you think?

Yes good point, I agree. 
Updated snippet:

```graphql
{ 
    Get (
        nearText: {
            concepts: ["Whta did the monkye do?", "Elon Musk"]
            spellCheck: {
                check: True,
                forceAutocorrect: True
            }
        }
    ) {
        Document {
            title
            _additional {
                spellCheck: {
                    originalText
                    didYouMean          # or a more normal name like `correctText`
                    corrected               # boolean - whether an autocorrect was applied
                    location                 # e.g. "nearText.concepts[1]"
                    numberOfCorrections
                    changes {
                        original
                        corrected
                    }
                }
            }
        }
    }
}
```

```json
{
    "data": {
        "Get": {
            "Document": [
                {
                    "title": "...",
                    "_additional": {
                        "spellCheck": [{
                            "originalText": "Whta did the monkye do?",
                            "didYouMean": "What did the monkey do?",
                            "numberOfCorrections": 2,
                            "changes": [{
                                "original": "Whta",
                                "corrected": "What" 
                            }, {
                                "original": "monkye",
                                "corrected": "monkey" 
                            }],
                            "location": "nearText.concepts[0]"
                        }]
                    }
                }
            ]
        }
    }
}
```

**Comment by bobvanluijt** [comment]
This one might work well, I just gave it a try :)

https://github.com/barrust/pyspellchecker

PS:
The script we use for C11y training could be used to create additional dictionaries as well
