### ISSUE TITLE
Pagination (from, to)

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1627]
If a root query (i.e., `{ Get { Class {}` has many results _or_ if a cross-reference contains many results, there is no way to request the results in a specific range (currently, this has to be solved after receiving the data on application level). Besides the technical implications (@etiennedi, @antas-marcin) I would like to understand what the potential UX (@laura-ham) implications are.

To kick off the discussion I would propose the following from an interface POV (described following Weaviate's [GraphQL design principles](https://www.semi.technology/developers/weaviate/current/architecture/interface.html#graphql-design-principles)):

```graphql
{
  <Function> {
      <Class>(
         form: int # <== FROM (optional)
         to: int   # <== TO (optional)
      ) {
        <property>
        <cross_reference-property>(
         form: int # <== FROM (optional)
         to: int   # <== TO (optional)
        ) {
            ... on <ClassOfBeacon> {
                <property>
            }
        }
      }
  }
}
```

**Comment by bobvanluijt** [comment]
Renamed to `Pagination`

**Comment by etiennedi** [comment]
## UX
- We already have a parameter `limit` to limit the sets of results, so `to` insn't needed (and would imho also be redundant)
- I'd suggest the more widely used `offset` instead of `from`. So `(offset: 100, limit: 10)` would retrieve results from 101-110
- Pagination on ref props creates a major UX problem in my opinion: The result list typically contains more than one result which all a very different amount of cross-refs. Their pagination would all be controlled by a single parameter (not good practice in my opinion) with varying effects depending on the number of refs. For example, if objects 1 has 100 refs, but object two has just 5, 9 of 10 pages would make sense for result object 1, but would show no results for object 2. A cross-ref pagination would in my opinion only have a clean UX if the root query has `limit:1` set. Furthermore, I can't think of a situation in an end application where the user would click on "next page" and expect multiple datasets to be paged. I think the intuitive expectation when clicking on "next page" is that exactly one thing is being paged. This makes me think that it might be 10 times cleaner to solve pagination of refs at the application level. 
- As a follow-up to the above, if we decide we want pagination on ref props, we also have to think about nested props. The confusion from above will only multiply if there is not one level, but many

## Technical
We need to be aware that with Weaviate being a distributed nosql db, pagination is essentially just querying more data and discarding the first results. Especially with multiple shards, shards will not know where the cutoff point is going to lie until they have been aggregated. So if a cluster has 10 shards, and you set `offset 100, limit 10`, Weaviate will retrieve a total 1100 objects (110 per shard) only to display 10 objects. In other words, the cost is high and increases with each page.

**Comment by etiennedi** [comment]
Mark as not stale. This is prioritized.

**Comment by eostis** [comment]
Great! I definitely need the pagination for a WooCommerce search & filters.

Is there a plan to release the fix soon?
