### ISSUE TITLE
Operator 'Not' not working

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#1717]
The 'Not' operator does not seem to have any effect (I could not find examples in documentation, so I guess my syntax is correct).

The following 2 filters should have opposite results, but give the same results (correct for the 'And', incorrect for the 'Not')

```
{
operator: And, 
operands: [
            {path: ["property"], operator: Equal, valueString: "xxxx"}
   ]
}

```
```
{
operator: Not, 
operands: [
            {path: ["property"], operator: Equal, valueString: "xxxx"}
   ]
}

```

**Comment by etiennedi** [comment]
@laura-ham I vaguely remember there being some back-story to the "Not" operator. I actually thought we had removed it completely, because we came to the conclusion that other operators could be used in it's place. Did we maybe forget to remove it? (That could explain why it's not explained in the docs)? Any idea on how to proceed?

**Comment by eostis** [comment]
Is it worth waiting for an implementation of the boolean 'NOT' in the future?
