### ISSUE TITLE
More verbosity when a Weaviate starts with a non-empty volume attached

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1741]
When starting Weaviate with a large dataset attached, the logs aren't very verbose.

It shows:

```
{"action":"config_load","config_file_path":"./weaviate.conf.json","level":"info","msg":"no config file specified, u
sing default or environment based","time":"2021-11-05T12:43:44Z"}
{"action":"startup","default_vectorizer_module":"text2vec-transformers","level":"info","msg":"the default vectorize
r modules is set to \"text2vec-transformers\", as a result all new schema classes without an explicit vectorizer se
tting, will use this vectorizer","time":"2021-11-05T12:43:44Z"}
{"action":"startup","auto_schema_enabled":true,"level":"info","msg":"auto schema enabled setting is set to \"true\"
","time":"2021-11-05T12:43:44Z"}
```

For a long time when data is loaded into memory (in my case about 185G).

Can the output be a bit more verbose on the status of the import? Or maybe even a `503` status code indicating that Weaviate is importing data into memory?

**Comment by etiennedi** [comment]
You can set the log level to `"debug"` and it will print periodic status updates about the size of the vector index. That's a nice way to see how the vectors are being loaded. To do so, set `LOG_LEVEL="debug"` as an env var.

A status code with a proper response would be even nicer, unfortunately, that's a bigger change because currently, the REST API doesn't even start up until the persistence layer is ready. Ideally, it would start up before but block all requests. But that's something we'd have to build first.

**Comment by bobvanluijt** [comment]
Haha `LOG_LEVEL="debug"` is _very_ verbose 😆 - thanks though

**Comment by bobvanluijt** [comment]
I'll close it for now

**Comment by etiennedi** [comment]
> Haha `LOG_LEVEL="debug"` is _very_ verbose 😆 - thanks though

That's the beauty of structured logging, every log has its own fields describing what it's about. You can simply filter for the ones you care about :) (You even get log aggregation for free if you run on managed K8s)
