### ISSUE TITLE
Enable multiple vectorizers with same searcher capabilities (e.g. nearText)

### ISSUE THREAD

**Issue by michaverhagen** [semi-technologies/weaviate#1744]
When using different vectorizors for different classes, it will only work if the modules use different property names. For example, if two modules both introduce a property `nearText`, then Weaviate will throw an error on startup.

**Comment by etiennedi** [comment]
One possible way to support this would be to deactivate `Explore` in such a case, since `Explore` will only make sense if all classes share the same vector space anyway. However, that's never the case with multiple models with conflicting capabilities, such as `nearText`, rendering `Explore` useless anyway. So instead of blocking the module startup, we could allow it and simply block `Explore`.

**Comment by etiennedi** [comment]
I've done a small experiment in https://github.com/semi-technologies/weaviate/commit/8e91cbdb2bee4a3610e151c245e3998cc9f0091a, I tried to see if disabling the validation would be enough to use multiple modules after I saw that the module provider already compares the configured vectorizer to the module. However, I ran into all kinds of weird errors, such as those:

![image](https://user-images.githubusercontent.com/8974479/145235549-5a11b88c-871f-4b2f-bbf9-c4ee8e98b93a.png)
![image](https://user-images.githubusercontent.com/8974479/145235563-9a8b6ab8-eac0-4e69-8e5b-37a84f5ab0e7.png)
![image](https://user-images.githubusercontent.com/8974479/145235590-5a4d1ddc-519a-497e-9c2c-77173c7f25e8.png)

My assumption is that `nearText` is somehow globally registered in the module system and then at query time it’s a random chance which one you’re going to get. But since it seems to be loaded multiple times, the chance that you get the right one multiple times in a row diminishes.

So to enable the above, we'd have to change the module system in a way where we don't just match the required logic by name (since that can be ambiguous) but somehow by using the configured vectorizer.
