### ISSUE TITLE
Switch off stalebot

### ISSUE THREAD

**Issue by WolfgangFahl** [semi-technologies/weaviate#1748]
The stalebot actions keep sending emails to me for unfixed issues such as #1682. It think it would be much better to switch off the stalebot.

**Comment by etiennedi** [comment]
Thank you for your feedback, we have discussed this internally and we see the value of the stale bot. I apologize for repeated notifications when something becomes stale. But for us, this is an important tool to prioritize. Most of the time, users lose interest in tickets they created. By requiring users to leave a quick comment a la "not stale", we know that they have in fact not lost interest and the issue is still relevant. This is common practice on most open-source projects and in my opinion a very small price to pay for being able to use cutting-edge software completely for free. Thanks for your understanding.

**Comment by WolfgangFahl** [comment]
You might want to change the message of the stalebot to ask uses for this reaction. Also changing the timing might help.

**Comment by etiennedi** [comment]
> You might want to change the message of the stalebot to ask uses for this reaction

Great idea! I've updated the message to make it a bit more friendly and explain the reasoning behind why the bot is marking issues as stale.
