### ISSUE TITLE
Add autocomplete

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#1763]
Something like:
![image](https://user-images.githubusercontent.com/1785759/145397443-1c84949b-f05b-4f49-b8cd-cd8460717605.png)

As I understand, this is different from the [spellcheck](https://www.semi.technology/developers/weaviate/current/modules/spellcheck.html) module which fixes search input lexical mistakes, but does not suggest keywords/sentences from the indexed text corpus.

**Comment by etiennedi** [comment]
Just to clarify: 

You are interested in "keyword matching" autocomplete, i.e. because the word `huggingface` is indexed, typing `hugg` should suggest it. This is something that could make use of the inverted index in Weaviate.

The reason I'm asking this is because the alternative would be using a neural model to predict the next word. E.g. something like typing `Where can I buy` and the model would predict `umbrellas` next. This is something that would require fine-tuning a model to the user's dataset first as it would act purely on training data, not necessarily on what the user has imported.

**Comment by eostis** [comment]
Both solutions look interesting. Of course, predictions are far more impressive. Can the training be somehow be "pre-integrated", like by calling some auto-ML solution (huggingface or other)? Perhaps some new modules "xxx fine-tuning"?

**Comment by mariusa** [comment]
> You are interested in "keyword matching" autocomplete, i.e. because the word huggingface is indexed, typing hugg should suggest it. 

This. 
The prediction request could be a separate issue. Though, `umbrellas` should also be indexed. No need to suggest terms which will have 0 results.

**Comment by etiennedi** [comment]
Keep open. This will be on the soon-to-be-released roadmap.
