### ISSUE TITLE
(improvement) Remove the model limitations in docker files

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#1797]
Currently, there can be only one module's model per docker file.

But sometimes we want to run a single docker instance with several module models, and create one class per module models.

For instance: 
- 3 transformer Vectorizer models: for a Q&A class, a NER class, and a search class.
- 2 Q&A reader models for different sections of a site

The hard-limit should only be "one vectorizer model per class", which is natural.
But in a docker file, there should be no limits on reader and vectorizer models.

**Comment by etiennedi** [comment]
This is a great idea and something that has already popped up on our slack and I also chatted with @antas-marcin about this very recently.

A few questions and ideas to make sure we're on the same page:

* When you refer to the "docker file", do you mean the Docker compose manifests, i.e. the `docker-compose.yml`? The actual [Dockerfiles](https://github.com/semi-technologies/weaviate/blob/master/Dockerfile) should not be involved in any such limitations?
* I think the limitation sits in how Weaviate treats the service discovery variables, not necessarily in composing the containers. The only real constraint there is unique names for the `services`, but the names are arbitrary. So, we could easily do something like `t2v-transformers-1`, `t2v-transformers-foo`, etc. Currently the blocking factor is that the service discovery variables, e.g. `TRANSFORMERS_INFERENCE_API: "http://t2v-transformers:8080"` have a global value. But I think we could easily configure them in a way where they work for mutliple cases.  For example we could use aliasing. It could look something like `TRANSFORMERS_INFERENCE_API: "transformers_foo=http://t2v-transformers-foo:8080, transformers_bar=http://t2v-transformers-bar:8080"`. Then when creating a class instead of referencing the global `t2v-transformers` module, users could vectorize the exact version they want. For example `"vectorizer": "text2vec-transformers[transformers-bar]"`, etc.

**Comment by eostis** [comment]
docker-compose.yml indeed!

The vectorizer is currently explicitly attached to the class definition. Perhaps we should do the same for the reader on each query?

- TRANSFORMERS_INFERENCE_API is now a default variable for each inference type (similar to DEFAULT_VECTORIZER_MODULE for classes)
- a new variable in queries enable to switch the reader (similar to vectorizer property for a class)

Example:
class1 {vectorizer: t2v-transformers-1}
class2 {vectorizer: t2v-transformers-2}

 t2v-transformers-1:
    image:model1
 t2v-transformers-2:
    image:model2
  qna-transformers-3:
    image: model3
  qna-transformers-4:
    image: model4

# Default reader
Get {
    class1(
       ...
)

# Specific Q&A reader
Get {
    class1(
     reader: qna-transformers-1
       ...
)

# Other Q&A reader
Get {
    class1(
     reader: qna-transformers-3
       ...
)

# Other vectorizer, but Q&A reader
Get {
    class2(
     reader: qna-transformers-1
       ...
)

I think this is very flexible: we can use default vectorizers and readers, or set the vectorizer on each class and the reader on each query.

**Comment by etiennedi** [comment]
Yes, good point. Anything that's not a vectorizer (i.e. that happens at runtime) can be overridden at query time. Only the vectorizers have to be set at import time.

**Comment by eostis** [comment]
The REST API should return all the vectorizers defined on the Weaviate instance, so one can choose in a list. Perhaps done with /v1/modules/, but I get a 404 currently.

The GraphQL should list all the readers for current class "reader" variable (but it's a given I suspect).
