### ISSUE TITLE
Bug: Autoschema not acting on batch reference

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1829]
TODO @etiennedi  Fill with content

**Comment by raam86** [comment]
Auto schema works in batch when objects are well formatted, however schema creation fails when objects contain illegal value, the error message that is returned is accurate but can be confusing: 

>(.venv) raam@Raams-MBP worst_song % /Users/raam/code/worst_song/.venv/bin/python /Users/raam/code/worst_song/minimal_example.py
[{"class": "TTNotExist", "creationTimeUnix": 1648809996753, "id": "ad3e6baf-de0d-43e9-a63c-08392c376d87", "properties": {"age": 35, "id": 44, "name": "Victor"}, "deprecations": null, "result": {"errors": {"error": [{"message": "'id' is a reserved property name, class 'TTNotExist' not present in schema, class NotExist not present"}]}}}, {"class": "NotExist", "creationTimeUnix": 1648809996753, "id": "abf5fd02-d7af-435a-9a6f-b2da24fc4e95", "properties": {"age": 45, "id": 55, "name": "Petra"}, "deprecations": null, "result": {"errors": {"error": [{"message": "'id' is a reserved property name, class 'NotExist' not present in schema, class NotExist not present"}]}}}]

A not so careful reading or new users can result in misunderstanding the underlying issue. The class is not present since it couldn't be created due to a different exception 
```
import json
import weaviate

def batch_result_debugger(result):
    print(json.dumps(result))

results = []
first = {"name": "Victor", "age": 35, 'id':44}
second = {"name": "Petra", "age": 45, 'id': 55}
results.append(first)
results.append(second)
client = weaviate.Client("http://localhost:8080")

with client.batch(batch_size=2, callback=batch_result_debugger) as batch:
    for track_props in results:
        batch.add_data_object(track_props, 'NotExist')
client.batch.flush()
