### ISSUE TITLE
Import Slow Down

### ISSUE THREAD

**Issue by murak038** [semi-technologies/weaviate#1840]
Hi,

I was trying to run the wikipedia demo on an AWS instance and was running into errors/slow down after I imported 12,000,000 paragraphs.

Instance Details:
g4dn.12xlarge
4 T4 GPUs
48 vCPU
192 GB RAM
Ubuntu 18.04 OS

After I import 12 million paragraphs, the machine performance considerably slows down. I start getting a batch creation timeout message for a batch size of 512, and I continue to get the message when I reduce the batch size to 50. Any ideas why the process slows down so much? The "vectorCacheMaxObjects": 150000000000 so I know that is not the issue.

**Comment by etiennedi** [comment]
Sudden slow downs (if not related to the `vectorCacheMaxObjects`) are not to be expected, so you are right to look for a source of those slow-downs. The two most common reasons for sudden slow downs that we've seen so far are:

* Potential for duplicate vectors. Duplicate vectors are a big problem for the HNSW index, it slows down considerably if there are exact copies of vectors. Is there any chance that your data contains duplicate vectors around the ~12M mark? Since you are mentioning the Wikipedia demo dataset this is unlikely, but we should still rule it out
* Could it be that the OS starts swapping memory to disk? As the memory requirements grow it might be the case that the OS suddenly decides to swap mem to disk. This would have a similar effect to limiting the `vectorCacheMaxObjects`. Is swapping configured and/or can you maybe even see if some pages are swapped?
