### ISSUE TITLE
Group filter (entity merging) - more advanced scenarios

### ISSUE THREAD

**Issue by ju-bezdek** [semi-technologies/weaviate#1938]
group filter as described here: https://weaviate.io/developers/weaviate/current/graphql-references/filters.html#group-filter-entity-merging

seems to be working OK only for strings and sort-of OK for dates (which are treated the same way as strings)

"merge"  command" with properties of other types returns wrong result in my opinion:

for instance wordCount in this example:

**numbers:** returns ... 872 ...is it an average?  there are articles with 1000+ wordCound... 

 **_additional {id}** returns always this: `"_additional": {  "id": ""   },`

referenced entities seem to work if there is no grouping going on... 
this works:
```
 group:{
        type: merge,
        force:0.055
      }
```
but this
```
group:{
        type: merge,
        force:0.55
      }
```
>> will fail: https://link.semi.technology/37RpRr7

I'd be awesome if I can get the actual data from group as array ... idealy as standard objects... so instead of grouping properties, you could just group the entities into list of list of similar docs... in a similar way how entity references are treated ... 

Another reasonable feature could be combing this with Aggregate{} syntax. For example, querying the number of docs in a group, retrieving a number of biggest groups of similar documents based on similarity.... there is plenty of interesting scenarios around this.

**Comment by lucas-cauhe** [comment]
Hi!
I think the issue here has to do with either instantiating a new Group object or appending it to a list (most likely the former) that one of these isn't following the datatype that makes it work when `force` value is low. 

Aside that issue, in your last paragraph, isn't that the intuition of clustering??
I have tested this grouping filter with a custom dataset against a k-medoids clustering implementation I did with the same dataset and it seems to be doing better.

Perhaps I'm not building good enough graphql queries 🙃, however with the results I'm getting I'm doing quite well.

And sure! I think this clustering feature could be awesome once enhanced and polished
