### ISSUE TITLE
Batch update functionality

### ISSUE THREAD

**Issue by navid-a** [semi-technologies/weaviate#1980]
This is a request for having a batch update feature, analogous to batch uploads.

There may be two issues built into this:
1. Updating existing fields for a batch of documents
2. Updating the schema as well in a batch update scenario.

----------------------------------------
See below for log of slack messages describing the intended use-cases:

Billy Kotsos: I was thinking about creating a vector with one piece of data like text- this would be something like 'user email', next I was thinking I would like to upload new data fields like time/classification labels from other models,etc...
I don't know everything I want to store at the start, so I was thinking of building up the DB incrementally. I think of it similar to adding a new column on a SQL table.

Navid Aghasadeghi: +1 on this request. I also find that I need to update the content of documents often or update the schema sometimes and the api for updating is generally not as featureful as the api for uploading.

**Comment by navid-a** [comment]
I will add another pain-point/improvement opportunity to this: In addition to batch update, it would be also super useful if the update function would do both add and/or update depending on what is needed.

This would mean we could always use the same function to upload or update and Weaviate will automatically add the document if it doesn't exist (this is similar to how for e.g. the google firebase api works.) I am working with a large database and continuously updating documents to Weaviate. While I have built a system to keep track of what documents have been uploaded, sometimes there are errors. So one solution is to always check if a document exists before uploading/updating, but that gets super slow.

So this feature ask would definitely help there.

**Comment by ju-bezdek** [comment]
This (batch partial update) would be really helpful...  I've found out that updating data by retrieving all to client, update and full update with batch update. It's still quite ineffective, memory intensive and potentially dangerous (since it takes 10minutes+ to perform this on 25k records, the data fetched locally could have been changed by then.

**Comment by ju-bezdek** [comment]
I want to keep it open ... and event bump up the priority if possible .. it takes 4hours to update about 130k of records currently...

Retrieving them in order to do a batch overwrite is supper inefficient, expecially if your objects are big and also dangerous because of the concurrency issue is much higher this way...

**Comment by billyg88** [comment]
Has this been addressed? :)

**Comment by ju-bezdek** [comment]
No, 
but a new [roadmap](https://weaviate.io/developers/weaviate/current/roadmap/feature-roadmap.html )
with voting for features was introduced and my version of this was put on backlog... 
[](https://github.com/semi-technologies/weaviate/issues/2124)

I was certain that this issue existed, but couldn't find it, so I've created my own as I was requested by weaviate team. My issue is on the backlog. Please consider voting for it. Maybe this issue should be put there instead of mine, since this one is older.

**Comment by etiennedi** [comment]
Hi @billyg88 and @navid-a 

As @ju-bezdek already mentioned there is another issue for this already. You can upvote the other one. Sorry for missing this one, but I agree that both are about the same. Please upvote #2124 to indicate your preferences for this.
