### ISSUE TITLE
General questions on your Distance Metrics support

### ISSUE THREAD

**Issue by songohannyc** [semi-technologies/weaviate#2297]
I'm new to vector database. I have some questions about Distance Metrics support.
Per this documentation, https://weaviate.io/developers/weaviate/current/vector-index-plugins/distances.html#available-distance-metrics
On dot inner product support, I have the following questions.
1. Can a and b be matrices? For example, a is NxM and b is MxP 
2. What is recommend operating range of M dimension?
3. Could you point me to performance metric documentation?
Thank you very much for your help.

**Comment by trengrj** [comment]
Summarising from Slack:

1. Weaviate does not support storing matrices instead of vectors but you could add a custom distance function (where a vector is represented as a flattened matrix).
2. There is no limit on dimension size in Weaviate but vectors embeddings usually range in size from 128 - 15,000 dimensions. OpenAI's GPT-3 davinci model has 12,288 dimensions as a large example. You will get better performance with smaller vectors.
3. Weaviate benchmarks https://weaviate.io/developers/weaviate/current/benchmarks/ann.html

**Comment by cceyda** [comment]
@trengrj Could you give a simple example on how to add a custom distance function?
