### ISSUE TITLE
(bug) nearObject is not commutative

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#2494]
Hi,

A dog not looking like a cat:
<img width="167" alt="image" src="https://user-images.githubusercontent.com/1785759/209847400-c691892c-08b9-4eba-8afb-127f1e3987b2.png">
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/1785759/209847694-e09df808-8375-4eb3-9c74-b87d9f63edb3.png">

But the same cat looking like the same dog:
<img width="176" alt="image" src="https://user-images.githubusercontent.com/1785759/209847810-0e62d241-28a2-4a25-b2da-a80cc28ea487.png">
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/1785759/209847779-df1752c2-3d51-4f9d-8f59-de4c8742b3ef.png">

(using a CLIP model)

**Comment by trengrj** [comment]
Hi @eostis, I think this is related to the underlying distance calculation rather than a bug in Weaviate. For example here are 5 random vectors with cosine distances:

When searching from index 0 (say the dog vector), index 1 (say the cat) is furthest away.
When searching from index 1 (the cat), index 0 (the dog) is no longer the furthest away.

<img width="790" alt="Screen Shot 2022-12-29 at 8 06 40 pm" src="https://user-images.githubusercontent.com/2173919/209936097-7b8eaea5-060d-4951-ab08-7eeb3d26a6cd.png">

**Comment by eostis** [comment]
Thanks. I can see it now.

dog------------------cat--bird

Distances from dog: cat bird
Distances from cat: bird dog
