### ISSUE TITLE
Improve testing story

### ISSUE THREAD

**Issue by moretea** [semi-technologies/weaviate#412]
We should introduce a proper [Testing Pyramid](https://martinfowler.com/articles/practical-test-pyramid.html).

![image](https://user-images.githubusercontent.com/99988/43192243-5b858b9e-8ffd-11e8-842d-52b7bd7dd027.png)

Some improvements that come to mind after trying to make the tests pass for #400:
- [ ] Do not make the tests depend on each other! Currently, only the whole test suite can be run. Also, this makes it impossible to run the tests in parallel.
- [ ] Use the auto generated API for integration tests
- [ ] Remove `time.Sleep`'s in the test code. Business logic, like key expiration,  are better suited to be moved to unit tests, where we can test more scenario's cheaply without resorting to tricks like waiting for a few seconds.

**Comment by etiennedi** [comment]
I agree that we should strive for being more aligned with the test period. At the same time, I'm aware that the cost of adding unit tests to existing code is often higher than writing that code itself. (unless it's very good code).

## Proposal
So, my pragmatic proposal would be: **Let's aim to unit-test new code, but accept that existing code is not always unit-tested.** This can also easily work when adding new methods to a previously untested struct (for example see https://github.com/creativesoftwarefdn/weaviate/commit/97dd6fa876635646d51d340dc21bb63c8fa4fa0a) This way, we don't add new tech debt and don't waste spend weeks on cleaning up existing debt. 

### Improvements down the line
Once we have many new unit tests, we'll automatically have much fewer requirements for higher-level tests (like acceptance, journey and integration tests): Because edge-cases are tested at a unit level, we'll only really need to verify one happy-path per feature at a higher level to prevent us from regressions on that feature. This should reduce the feedback cycle times dramatically.

Personally I prefer test-driven development, but don't think we should make this an overall rule or even guideline - as the learning curve can be quite steep. The goal right now is the improve the (useful) unit-test coverage on newly added code and in turn balance out the pyramid. This way we don't have special tickets only to "fix tests" and therefore don't waste time and money on "non-functionals". 

@moretea has already introduced a pattern of keeping packages very small with clear boundaries, for example: https://github.com/creativesoftwarefdn/weaviate/blob/3a5777303a6d1c93d0b3383064bb4b561ed546f8/graphqlapi/local/get/get.go#L1
I think we should keep up this pattern of isolation, as it also makes testing much easier - which can only be a good sign.

### Test style ("native" vs. framework)
I've made good experiences with BDD-style testing in Golang before (using [Ginkgo](https://onsi.github.io/ginkgo/) ) before, but I'd actually advise against introducing a new style/framework right now and stick with the default go testing methods. Only once we run into limitations there, would I recommend considering a BDD framework like Ginkgo.

**Comment by etiennedi** [comment]
I've also noticed that a simple `go test ./...` leads to failures, because it includes the acceptance tests. I assume that the acceptance tests can only run inside a `docker-compose` setup?

I would propose to flag all tests with buildConstraints, such as `// +build unitTest` or `// +bulild acceptanceTest`. This way you can selectively run whatever tests you want using `go test -tag unitTests ./...`, etc.

@moretea How do you currently run all unit tests? Are they currently run separate from the acceptance tests on CI?
