### ISSUE TITLE
Create Swagger examples based on Zoo-Demoset

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#560]
The swagger doc should contain examples based on the Zoo Ontology.

Explanation video can be found [here](https://drive.google.com/a/semi.network/file/d/1-oYnsEIW5Z1ZVOOShCSrPv1jF9L3zHVC/view?usp=sharing).

**Comment by laura-ham** [comment]
I've added some examples in the open api documentation.

A few questions/issues raised:
-	Key object in Get Things, is that the key of the user or the uuid of the Thing?
- 	Cannot add examples for parameters (result in error)
-	Patch value is always an object (so always a reference)? Can't it be just a string/number etc?
-	Cannot remove 'from' from the body of Patch in the example body
- 	Example result does not show props if there is also a ref (KeyTokenGetResponse)
	-	And if this would be shown, what is difference between 'key'(token) and 'id of key'(keyId)
- 	Don't know how to add arrays in examples, so schema and examples are not consistent because there is only one property and one class.
-	What is the 'knowledge tools' query? 
-       Are we going to use Openapi 2.0 or 3.0? Because some of the problems described here may be solved when we change to version 3.0.

I guess most of these questions need to be illustrated with examples to understand what I mean, maybe it is good to schedule a short call @bobvanluijt?

**Comment by bobvanluijt** [comment]
Hi @laura-ham, sure, we can go over them, already some feedback per bullet;

1. That is the key of the user. _However_ we will remove keys completely in the near future (cc: @etiennedi )
2. Can you share the exact error or how to reproduce it?
3. Yes
4. Can you share the exact error or how to reproduce it?
5. See bullet 1.
6. Can you share how far you've gotten?
7. I'll update this one, it is new and I need to write docs and all.
8. 2.0 because of Go-Swagger [[ref](https://github.com/go-swagger/go-swagger/issues/1122#issuecomment-356086493)].

**Comment by etiennedi** [comment]
@laura-ham @bobvanluijt Do we still need to do anything here or can we close this?

**Comment by etiennedi** [comment]
Closing as docs related things are now part of the website.
