### ISSUE TITLE
GetMeta & date type

### ISSUE THREAD

**Issue by moretea** [semi-technologies/weaviate#601]
### Query
```graphql
{
  Local {
    GetMeta {
      Actions {
        Flight {
          date {
            count
            type
            topOccurrences {
              value
              occurs
            }
          }
        }
      }
    }
  }
}
```

This is copied from how a string is handled, is this appropriate for dates @laura-ham?

**Comment by laura-ham** [comment]
Good question @moretea. Dates are handled as strings by GraphQL, that's why it is currently implemented in the prototype like this. But I agree that we could offer more than this :)

We could add fields for `firstDate` and `lastDate`? Should we also consider more elements of the `Date` datatype (because it's rich of info) or would that be too specific? E.g. `averageTime`, `topOccurrences{month}` etc.

```graphql 
{
  Local {
    GetMeta {
      Actions {
        Flight {
          date {
            count
            type
            topOccurrences {
              date {
                value
                occurs
              }
              day {   # also for month and year
                value
                occurs
              }
              hour {   # also for second and minute
                value
                occurs
              }
            }
            firstDate
            lastDate
          }
        }
      }
    }
  }
}
```

**Comment by bobvanluijt** [comment]
Is this still relevant @laura-ham or @moretea?

**Comment by laura-ham** [comment]
> Is this still relevant @laura-ham or @moretea?

Yes, this is opened a day ago and would be nice if someone could reply on my comment. @moretea @JeroenStravers1 @bobvanluijt

**Comment by etiennedi** [comment]
Closing as this doesn't seem like a pressing issue. The general idea still makes sense, so happy to see this reopened if we have demand for it.
