### ISSUE TITLE
Resolve Network.Introspect

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#648]

**Comment by etiennedi** [comment]
@laura-ham Some time ago, we talked on Slack about merging `Network { Introspect }` with `Network { Fetch }` (and the same for Local). I was just about to get started with this and was wondering if this proposal still needs discussion or if I can just get started and we refine it afterwards based on feedback?

My plan is to simply merge them, so that the additional step of putting the beacon into `Introspect` will be omitted and instead `Fetch` will show the results that `Introspect` would have otherwise shown.

**Comment by laura-ham** [comment]
Yes let's do that!

Two points:
- We currently don't have a Local Fetch, so we need to make this as well.
- And indeed Network Introspect will be omitted then, but also the Network Introspect Beacon (https://github.com/creativesoftwarefdn/weaviate/blob/master/docs/en/use/graphql_network.md#introspect-a-beacon)? Because we lose this functionality than.

**Comment by etiennedi** [comment]
Obsolete, `Network { }` API has been removed. Closing.
