### ISSUE TITLE
monitoring service

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#699]
# Description

The following needs to be sent as an https POST to a _to be determined_ HTTPS endpoint;
1. Information per API endpoint _except_ the `/graphql` endpoint.
2. Information per GraphQL function + aggregation function

# Sending an Object

With an interval of 300 seconds, the following object needs to be sent out;

```js
[{
    "n": "name", // name of the Weaviate. Is `a-b-c` where a, b, and c are random words from the contextionary.
    "t": "REST or GQL", // if a RESTful call add `REST` if a GQL call add `GQL`
    "i": "weaviate.x.y.z", // name of the request
    "a": 1 // amount of time the request happend within the 300 second interval,
    "w": 12345 // timestamp
}]
```

### Legend

1. n = name
2. t = type
3. i = identifier
4. a = amount
5. w = "when", time stamp.
### About the identifier

The name (== operationId in Swagger) is available through the schema.json (swagger) file. For example: `weaviate.actions.list`

With GQL you can append the root function, the secondary function and the aggregate function should be added between brackets.

1. Without aggregate function 1: `weaviate.graphql.post.local.get`
1. Without aggregate function 2: `weaviate.graphql.post.network.getMeta`
2. With aggregate function 1: `weaviate.graphql.post.local.get[sum]`

If one request contains multiple functions (as described as above), they should be added as a separate array or line items.

### About weaviate.graphql.batch

`weaviate.graphql.batch` should be defined as multiple `weaviate.graphql.post` requests.

# If the endpoint is not available (aka failsafe mechanism)

If the endpoint is blocked or not available the following should happen (NOT when the endpoint is available);

1. Append data as a CSV line to `/var/weaviate/usage.log`
2. Docker container should export `/var/weaviate/usage.log` outside the container.

# todo

1. Add the described functionality.
2. Send through the data to the _to be determined_ endpoint in [CBOR](http://cbor.io/) format.
3. Creat the failsafe mechanism as described above.
4. Add to docs what the mechanism does.
5. Tests, tests, tests

# important

Data from the ontologies or graphs should _never_ be send out.

**Comment by JeroenStravers1** [comment]
Function calls will be logged in a hashmap (access controlled via mutex). This allows for flexibility in adding/editing request types. 

Should performance become an issue then there are options for optimization, like using a rw-locked hashmap for each main request type (localget, networkget, networkgetmeta, etc). This would mean that we'd lose some flexibility in changing request types.

**Comment by JeroenStravers1** [comment]
@bobvanluijt you stated that logging only needs to go two levels deep (level one: `local`/`network`, level two: `get`/`getmeta`/`fetch`/`aggregate`/`introspect`) and that I should also log the aggregate function calls. However, the way our schema is structured these aggregate functions are attributes of the `Things` and `Actions` at the third level. **Should I log two or three levels deep?** The aggregate functions get interpreted in the `Thing`/`Action` resolvers, so that's where I'm placing logging for now. This is at third level depth.

Two examples to clarify:

### GQL Get request
Say we receive this query:
```
{
  Local{
    Get{
      Things {
        City {
          population
          }
        Aircraft {
          name
          }
        }
      }
    }
  }
}
```
If I understand you correctly we'd want to log:
- 1x `"weaviate.local.get"`

However, because the resolvers live on the Things/Actions level we'd log a `Get` call for `City` and for `Aircraft`:
- 2x `"weaviate.local.get"`

### GQL Aggregate request
What should I log if we get this query:
```{
  Local{
    Aggregate {
      Things {
        City(groupBy: ["isCapital"]) {
          population {
            sum
            maximum
          }
        }
        Airplane(groupBy:["isAirborne"]) {
          passengers {
              sum
              count
            }
          }
      }
    }
  }
}
```
Since resolvers live at the Thing/Action level, we'd log:
- 2x `"weaviate.local.get[sum]"`
- 1x `"weaviate.local.get[max]"`
- 1x `"weaviate.local.get[count]"`

But, as it's only a single Get request (2nd level), shouldn't this be:
- 1x `"weaviate.local.get[sum]"`
- 1x `"weaviate.local.get[max]"`
- 1x `"weaviate.local.get[count]"`
?

**Comment by JeroenStravers1** [comment]
Just a thought: Using (only) 3rd level logging prevents us from determining the total number of GQL requests made.

**Comment by bobvanluijt** [comment]
Hi @JeroenStravers1, 

Good question, the `serviceId`'s should be based around the _query_ rather than the traversing. So for your latest example, you can go for:

- 2x "weaviate.local.get[sum]"
- 1x "weaviate.local.get[max]"
- 1x "weaviate.local.get[count]"

Does that answer your question?

**Comment by JeroenStravers1** [comment]
Hey @bobvanluijt, that definitely helps, thanks! What should I log in the first example?

**Comment by bobvanluijt** [comment]
- 2x "weaviate.local.get[sum]"

**Comment by etiennedi** [comment]
Closing as complete.
