### ISSUE TITLE
Calculate "result certainty" in fetch queries

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#710]
The `Fetch {}` implementation done in #645 does not currently return a certainty of a found result. This is because we don't have a model on how to calculate this

## Todos
* [ ] design simple model how certainty in result should be calculated (@laura-ham)
* [ ] implement model (@etiennedi)

**Comment by laura-ham** [comment]
We have a few variables:
- The certainty of the returned class, based on the classname and its keywords
- The certainty of each property, based on the property name, it keywords, and the value.

We could calculate the final certainty in the reverse way we calculate distances out of the given `certainty` in the query. So that means that we need to calculate the distance between de returned Things/Actions and the query. This distance could be a weighted average distance between all the variables mentioned before (class&props). 

All variables have a distance between the queried value and the returned value. For example:
- Queried was `City`, with the keyword `Town`, but returned was `Village`. The distance here is 0.1.
- Queried was `population` but returned was `inhabitants`, the distance here is 0.2.
- Queried was `name`, but returned was `identifier`, the distance here is 0.3. 

We could use calculate the weighted average:
distance = w_class * d_class + w_props/n_props * ( sum(d_prop) )

where 
- w_class = weight attributed to the class distance
- d_class = distance between the queried and calculated class
- w_props = weight attributed to all props in total
- n_props = number of properties
- d_prop = distance between a queried and calculated property

Applied to the example:
distance = w_class * 0.1 + w_props/2 * ( 0.2 + 0.3 )
distance = w_class * 0.1 + w_props/2 * 0.5
Let's say we have class always 50% weight and properties the other 50%:
distance = 0.5 * 0.1 + 0.5/2 * 0.5
distance = 0.175

This is the weighted average distance. We can than map this back to a `certainty` using the same model (linear/logarthmic/exponential) as we use for `certainty`->`distance`. 

We could start with setting the class match importance equal to the properties (both 50% as in the example), but it will need some trials to find the optimal ratio.

What do you think?

![img_20190215_104159929](https://user-images.githubusercontent.com/26965746/52848196-6a0c3980-310e-11e9-9f83-83b349ffc449.jpg)

**Comment by laura-ham** [comment]
Also, what comes to my mind now is that the `certainty` in the query filter has a different meaning than the `certainty` in the query result. In the filter it means how certain _you are_ that a class/prop is named like this, while the result is more like a _match rate_. So the user cannot specify what the minimal certainty of the result should be, only how certain the user is. 
This is just a random thought, I don't know if we should do something with it.

( 
What if we give the user the option to ask for a 'total certainty' instead of certainty for the class and every property. It would be easier for the user to understand and make queries, but the results might be less specific and accuracy because the user can specify less details. 

That would be something like:
``` graphql
{
  Network {
    Fetch {
      Things(where: {
        class: {
          name: "Animal",
          keywords: [{
            value: "Mammal",
            weight: 0.9
          }],
        },
        properties: [{
          name: "name",
          keywords: [{
            value: "identifier",
            weight: 0.9
          }],
          operator: Equal,
          valueString: "Bella"
        }]
      }, minimal_certainty: 0.8) {
        beacon
        certainty
      }
    }
  }
}
```

instead of
```graphql
{
  Network {
    Fetch {
      Things(where: {
        class: {
          name: "Animal",
          keywords: [{
            value: "Mammal",
            weight: 0.9
          }],
          certainty: 0.8
        },
        properties: [{
          name: "name",
          keywords: [{
            value: "identifier",
            weight: 0.9
          }],
          certainty: 0.8,
          operator: Equal,
          valueString: "Bella"
        }]
      }) {
        beacon
        certainty
      }
    }
  }
}
```
)

**Comment by etiennedi** [comment]
Thanks a lot for your input, @laura-ham. I haven't been able to focus on this part yet. I like your weighted distance proposal, though. I'm currently not sure how feasible this is from a technical perspective with the current connectors, since we don't see which property matched. However, this is a problem we can solve. As of now (MVP timeline) we don't return certainties yet. I'll come back to this some time after the MVP.

**Comment by etiennedi** [comment]
Closing as fetch has been removed/replaced by the re-focus of "explore concepts". Therefore closing as obsolete.
