### ISSUE TITLE
GetMeta errors when count == 0

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#775]
From https://github.com/SeMI-network/playground/issues/92

Original Issue:

> @etiennedi could you check why the following query on http://35.204.85.213/?weaviateUri=http%3A%2F%2F35.204.85.213%3A8080%2Fweaviate%2Fv1%2Fgraphql&graphiql=true gives an error:
> 
> ```
> query MetaDataForFilter {
>   Local {
>     GetMeta {
>       Things {
>         Shop {
>           name {
>             count
>             topOccurrences {
>               value
>               occurs
>               __typename
>             }
>             type
>             __typename
>           }
>           __typename
>         }
>         __typename
>       }
>       __typename
>     }
>     __typename
>   }
> }
> ```
> Response:
> 
> ```
> {
>   "data": {
>     "Local": {
>       "GetMeta": {
>         "Things": {
>           "Shop": {
>             "__typename": "MetaShop",
>             "name": {
>               "__typename": "MetaShopnameObj",
>               "count": null,
>               "topOccurrences": null,
>               "type": "string"
>             }
>           },
>           "__typename": "WeaviateLocalGetMetaThingsObj"
>         },
>         "__typename": "WeaviateLocalGetMetaObj"
>       },
>       "__typename": "WeaviateLocalObj"
>     }
>   },
>   "errors": [
>     {
>       "locations": [
>         {
>           "column": 13,
>           "line": 7
>         }
>       ],
>       "message": "sourcemap has no field 'count', got map[string]interface {}{\"type\":\"string\"}",
>       "path": [
>         "Local",
>         "GetMeta",
>         "Things",
>         "Shop",
>         "name",
>         "count"
>       ]
>     }
>   ]
> }
> ```

**Comment by etiennedi** [comment]
@dljcollette Bugfix is ready on a branch. However before I merge this, I have an API question for @laura-ham:

What should the null value for all the `GetMeta` props be? Right now everything is explicitly `null`, which might make sense in some cases, but be confusing in others. Let me demonstrate with some examples:

### Scenario: No cars, `GetMeta { model { count } }`
Option A: There are no cars, therefore there can't be any cars that have the a `model` property set, so the count must be `0`
Option B: There are no cars, therefore I cannot compute any analysis on `model`, therefore the count is `null` (<-- currently the case)

In this example I find Option A more intuitive. However if we exchange count for another prop it isn't so easy to say:

### Scenario: No cars, `GetMeta { weight { mean, sum, max, min } }`
Option A: `mean: 0, sum: 0, max:0, min: 0`. 
Option B: `mean: null, sum: null, max:null, min: null`

In this case I find Option B much more intutive, because we didn't have any cars, so saying "there is no average weight" for cars is much more accurate then saying "the average car in our data set weights 0kg"

### This boils down to ...
Essentially this boils down to: What are the zero values of our types? 
Option A represents "The zero value of all number/int types is 0"
Option B represents "Numbers and int are nullable"

Which do we want to go for? Whatever we decide we should probably make it consistent and also add a column in [this table in the docs](https://github.com/creativesoftwarefdn/weaviate/blob/master/docs/en/use/ontology-schema.md#property-data-types) explaining what the zero value of each type is.

Screenshot of current Implementation:
![image](https://user-images.githubusercontent.com/8974479/54155840-3ee2e480-4445-11e9-827a-9805a99872ae.png)

**Comment by laura-ham** [comment]
@etiennedi 

At first, without looking at Scenario 2, I also thought option A for Scenario 1 is most intuitive. However, the `count` of `model` is not `0`, it instead does not exists, because there are no cars, just like in Scenario 2. A `0` would namely also be returned if there are cars, but no car instance has its model specified.

If there are cars, but no car has a `weight` specified, then the values `mean, sum, max, min` should return `null` as well, but `count` should resolve in `0`.

So intuitively I would say, if there are no instances of a class at all, all values should return `null`.
But this comes down to the following (inconstistent for the `count`) design:

**No instances of the class (no cars):**
* `meta {count}` == `0`
* `prop {count}` == `null`    **<====== or `0` ?** (*)
* `prop {<all other things like sum and max, except for type>}` == `null`

**There are instances of the class, but the property is not filled for any instance**
* `meta {count}` == `5`
* `prop {count}` == `0`
* `prop {<all other things like sum and max, except for type>}` == `null`

What do you think? `null` or `0` for the (*) line?

**Comment by dljcollette** [comment]
@etiennedi thank you for your solution. This would work for me. Having no error message is most important. I'll add some extra checks for null values in Playground.

**Comment by etiennedi** [comment]
Closing as complete.
