### ISSUE TITLE
Add C11y string validation to config file

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#820]
Add string validation to the config file and implement when adding strings.

The goal of this function is that a string that is added should -optionally- be validated again the C11y. Same functionality as `operationId: weaviate.c11y.corpus.get` should be used.

TODO:
- [ ] Add config option
- [ ] Integrate the validation per function

**Comment by etiennedi** [comment]
We might need this a bit more granular than just force vs no-force. Let's say we have a large dataset of artworks. Each artwork is described with human language very well in a description field, so we want to benefit from validating that the description is entirely contained in the contextionary. However, the artworks might have names that aren't real words from the dictoniary. So in this case it would be quite beneficial make sure `description` is validated, but `name` is not.

So we could:
- Either make the validation required per property rather than globally
- Have a global setting, but allow local overrides for each property

**Comment by etiennedi** [comment]
Closing as the same goals have been implemented differently in the meantime (`index`, `vectorizePropertyName`, etc)
