### ISSUE TITLE
Delay after adding thing or action

### ISSUE THREAD

**Issue by dljcollette** [semi-technologies/weaviate#822]
There seems to be a delay in updating the complete list of things and actions. As a result, I'm unable to fetch a newly added thing or action. The Weaviate instance that I was working with did not contain more than 5 things.

1. [Add a new thing or action](https://app.swaggerhub.com/apis/bobvanluijt/weaviate/0.12.70#/actions/weaviate.actions.create)
2.  [Request all things or actions](https://app.swaggerhub.com/apis/bobvanluijt/weaviate/0.12.70#/actions/weaviate.actions.list), right after receiving a `200` response status on step 1.

The recently added thing or action is not in the list of all things and actions. However, it is there when I try the request a few seconds later. I would expect my recently added thing or action to be in the request for all things or actions immediately after a successul response.

**Comment by etiennedi** [comment]
This is to be expected with the janusgraph connector for all requests other than getting a thing by its uuid ID. This is because the only index we have in Cassandra itself is for UUIDs. All other indices are coming from Elasticsearch and Elasticsearch needs some time to build the indices. This time however can be configured, so it might help to reduce it, in cases where the playground is used. According to the Elasticsearch docs it defaults to 1s:

```
index.refresh_interval
    How often to perform a refresh operation, which makes recent changes to the index visible to search. Defaults to 1s. Can be set to -1 to disable refresh.
```
https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#dynamic-index-settings

This is something where SeMI's solution engineering team can guide a potential user. They will probably want a very small delay when adding things interactively through the UI, but will want a very big delay when adding things in bulk (to reduce the overhead of constant re-indexing).

We could try setting it to a very small timespan, but I don't think we'll get atomic indexing.

**Comment by etiennedi** [comment]
Closing. While the eventual consistency of Elasticsearch is something that is central to our stack and can't be changed, we introduced #980 which makes the above much less noticeable.
