### ISSUE TITLE
Not possible to set CREFs with cardinality many

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#868]
_Related to: https://github.com/semi-technologies/weaviate/issues/756_

**Currently, it is not possible to set CREFs where cardinality is set to _many_.**

## Replicate

Part of `/meta`

```json
{
    "class": "City",
    "description": "A city  in a country",
    "properties": [
        {
            "cardinality": "atMostOne",
            "dataType": [
                "string"
            ],
            "description": "The name of the city",
            "name": "name"
        },
        {
            "cardinality": "atMostOne",
            "dataType": [
                "Country"
            ],
            "description": "The country of the city",
            "name": "inCountry"
        },
        {
            "cardinality": "many",
            "dataType": [
                "Place"
            ],
            "description": "The places related to this country",
            "name": "hasPlaces"
        }
    ]
}
```

1. Settings via POST fails as outlined here: https://github.com/semi-technologies/weaviate/issues/756
2. Via `PATCH` also fails although the server response is `200`.

```
url: http://localhost:8080/weaviate/v1/things/[someId]

body: [
    {
        "op": "add",
        "path": "/schema/hasPlaces",
        "value": {
            "$cref": "weaviate://localhost/things/[someId]"
        }
    }
]
```

Result:

```json
{
    "class": "City",
    "id": "[some id]",
    "lastUpdateTimeUnix": 1557704070547,
    "schema": {
        "hasPlaces": {
            "$cref": "weaviate://localhost/things/[some id]"
        },
        "inCountry": {
            "$cref": "weaviate://localhost/things/[some id]"
        },
        "name": "Cádiz"
    }
}
```

⬆️ this is correct, however, when doing a GET on this `thing` the `hasPlaces`  property is not available.

PS:
Also note how the cardinality is set to `many` but the result is an object and not a list.

**Comment by etiennedi** [comment]
The PATCH payload specified above is incorrect, because it tries to add an object for `schema/hasPlaces`. However, since the cardinality is set `many`, we need an array.

There was some broken error handling, which is why you were never informed about the invalid payload. I'm fixing this as part of this issue.

In the meantime you could use the following approach, but I admit that it's a bit cumbersome, which is why I'll prioritize the fix for #756.

## A working way to add multiple refs via patch at the moment.
Unfortunately for this approach adding the first reference is a different behavior than adding subsequent refs. Nevertheless it works, so it should be suitable to unblock you until I have fixed #756:

### Add the first ref by adding an array:
`PATCH /weaviate/v1/things/{id}` with body:
```json
[
    {
        "op": "add",
        "path": "/schema/hasPlaces",
        "value": [
          {
            "$cref": "weaviate://localhost/things/[someId]"
          }
       ]
    }
]
```

Please note that `"value"` contains an array!

### Add another ref by appending to the existing array
`PATCH /weaviate/v1/things/{id}` with body:
```json
[
    {
        "op": "add",
        "path": "/schema/hasPlaces/-",
        "value": {
            "$cref": "weaviate://localhost/things/[someId]"
        }
    }
]
```

Please note that the two changes as compared to above:
* `"path"` now contains a `/-` indicating that we want to append to the existing array at the last position
* `"value"` is no longer an array, as we are no longer setting the entire value key, but appending to the existing value array

**Comment by etiennedi** [comment]
Removing the blocker label, as an alternative fix is outlined in the previous post.

**Comment by bobvanluijt** [comment]
Ok, clear. Thanks. Would indeed appreciate the priority regarding the UX.

**Comment by etiennedi** [comment]
Closing as the broken error handling was fixed.
