### ISSUE TITLE
Explore{} functionality

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#883]
Because the concepts (aka _things_ and _actions_) are being stored in the vector space, we can explore Weaviate in a different fashion than traditional searches.

Birds-eye view;
- Rename `Local -> Fetch -> Fuzzy` to `Local -> Explore -> Concepts`
- Explore both concepts via beacons as things and actions directly

## Explore function in GQL

On the highest level, the new functionality looks like:

```graphql
{
  Local{
    Explore{     # <== Explore is the new syntax, because one "explores" Weaviate.
      Concepts{} # <== Concepts returns beacons. It can be anything of an unknown origin.
    }
  }
}
```

## `Concepts{}`

Schema with example input;

```graphql
{
  Local{
    Explore{
      Concepts(
        keywords: ["GTA", "5", "reviews"],
        limit: 100,
        moveTo: {
      		words: ["positive"],
		force: 0.5
        },
        moveAwayFrom: {
      		words: ["epic"],
		force: 0.25
        }
      ){
        beacon
        className
        distance
      }
    }
  }
}
```

- **keywords** = an array of strings where every individual string represents a vector space (or not). When multiple words are in one string (e.g., `keywords: ["monkey dance"]`) the centroid of the words will be taken as the input vector. Resulting in different results when they are separated (e.g.,  `keywords: ["monkey dance"]` versus  `keywords: ["monkey", "dance"]`)
- **limit** = maximum results.
- **moveTo**: when a centroid is calculated based on the keywords _`k`_, one can move towards direction _`T`_ where the force _`f`_ is a maximum of half the distance resulting in: ~~`(k+T)/2*f` For example: if _`k`_ = 1, _`T`_ = 20, _`f`_ = 1.0. The search centroid will be placed at vector 10.5.~~ For updated formula, see https://github.com/semi-technologies/weaviate/issues/883#issuecomment-505341066
- **moveAwayFrom**: is similar to `moveTo` but moves away resulting in: ~~`k-(k+T)/2*f`. For example, if _`k`_ = 1, _`T`_ = 2, _`f`_ = 1.0. The search centroid will be placed at vector -0.5.~~
- **beacon**: Beacon -as currently used- that points to a concept.
- **className**: Name of the local class the beacon points to.
- **distance**: How far is it from the search vector point? (previously known as _relevancy_)

## Notable

1. For Things and Actions using the explore function directly we have: https://github.com/semi-technologies/weaviate/issues/881

## Open TODOs
This was partially implemented as #888, but some features are still missing for completion:

* [x] implement movements
  * [x] in vectorizing logic
  * [x] in use case (traverser)
  * [x] in GQL API
* [x] include distance in results
* [x] respect limit
  * [x] in API
  * [x] in vector search
* [x] add/fix description in all gql fields

**Comment by etiennedi** [comment]
@bobvanluijt Quick question regarding

> When multiple words are in one string (e.g., keywords: ["monkey dance"]) the centroid of the words will be taken as the input vector. Resulting in different results when they are separated (e.g., keywords: ["monkey dance"] versus keywords: ["monkey", "dance"])

If they're all in one string (array item) we built the centroid, understood. What is supposed to happen if they are separate elements?

**Comment by bobvanluijt** [comment]
Let's take the following two keywords:
1. `keywords: ["monkey dance", "tango"]`
2. `keywords: ["monkey", "dance", "tango"]`

The following would happen;
1. First, the centroid of _monkey_ and _dance_ is created. Secondly, the centroid of the _monkey dance centroid_ + _tango_ is created (two-dimensional centroid).
2. A centroid of _monkey_, _dance_ and tango is created (three-dimensional centroid).

**Comment by etiennedi** [comment]
I see, thanks. So without a 2nd/3rd arg the following would lead to identical results, correct? (At least as long as the contextionary only supports single words.)

1. keywords: ["monkey dance"]
1. keywords: ["monkey", "dance"]

**Comment by bobvanluijt** [comment]
Correct

**Comment by etiennedi** [comment]
@bobvanluijt I have two questions regarding the "moving to" and "moving away" forumula. You proposed the following:

> `(k+T)/2*f` 

**Question 1**
First up this way of writing is a bit misleading as this literally means `(k+T)*f / 2`, however, because of the order you wrote it the intention might have been to mean `(k+T) / 2f`. Which one did you mean? Either way though, I can construct the next example to be potentially problematic with this formula:

**Question 2**
However, I'm not sure if it's the best idea to divide (or multiply) the entire vector by the force. As we approach smaller forces the vector would be come infinitely small (with `(k+T)*f / 2`) or infinitely big with `(k+T) / 2f`. For example take the following situation:

- `k=5`
- `T=1`
- `f=0.0001`

Since the force is very small, we would expect that the resulting search vector is very close to the original keywords. We only moved a tiny bit towards the "moveTo". However, with the above formula we would actually result in:

Option 1: `(5+1)/2  * 0.0001 = 0.0003`
Option 2: `(5+1)/(2 * 0.0001) = 30,000.00`

Both are quite far from the original vector. I would thus propose to change the formula to the following, which is basically a weighted average:

`k * ( 1-f/2 ) + (T *f/2 )`

- With the above example we would end up with `5 * (1-0.0001/2) + 1 * (0.0001 / 2) = 4.9998` and indeed very close to the original keyword. 
- With an example for "full force", we would end up with `5 * (1-1/2) + 1 * (1/2) = 3` which is indeed much closer to the move to example.

Interested to hear your thoughts.

**Comment by bobvanluijt** [comment]
Thanks for sharing @etiennedi, let me try to answer all open questions in one.

The suggested movement formulas were hypothetical, I have not been able to test them. The problem here is that it is _very_ hard to be deterministic about the results. We use intuition to determine if the presented beacons make sense. Long story short, feel free to tweak and adjust the formula to get to intuitively satisfying results. Your last suggestions make complete sense to me.

PS:
I'm not sure I understand the question no.1 for me this is potato, potato 😁

**Comment by etiennedi** [comment]
Thanks for the answer :)

> I'm not sure I understand the question no.1 for me this is potato, potato 😁

Just for completeness sake (even though it doesn't really matter anymore now), these were the two different options you could have potentially meant:

![IMG_5137](https://user-images.githubusercontent.com/8974479/60082997-303ee580-9735-11e9-9d7d-cd659b631e94.jpeg)

**Comment by bobvanluijt** [comment]
Ha, thanks

**Comment by etiennedi** [comment]
@bobvanluijt FYI: As of the latest commit (see above), the **distance in the search results is now displayed as a normalized value between 0 and 1** (0 meaning search and result vector are identical, 1 meaning they are perfect opposites). The value is calculated based on cosine similarity which is also what we are using to score the vectors inside the Elasticsearch backend.

**Comment by bobvanluijt** [comment]
Check, thanks @etiennedi. Is this also in the docs?

**Comment by etiennedi** [comment]
@bobvanluijt Not yet, I just wanted to add it, but realized that the docs are currently still focused on the `Fetch` functions alltogether. This means the entire section needs to be rewritten to remove `Fetch Fuzzy` include `Explore Concepts` and the explore Operator. I think it would be best to group those in a small documentation issue. (I'll create it). This is also something @laura-ham could potentially help with if she has some time.

**Comment by bobvanluijt** [comment]
Ok thanks.
