### ISSUE TITLE
Suggestion: Explore functionality in operator path

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#896]
Suggestion: add explore functionality to the `Get{}` function.

===

The operator paths look like this:

```graphql
{
  Local{
    Get{
      Things{
        Place(where:{
              operator:Equal
              path:["name"]
              valueString: "Netflix"
            }){
          name
        }
      }
    }
  }
}
```

There is an opportunity to include the C11y functionality as a value.

Concept:

```graphql
where:{
    operator:Equal
    path:["name"]
    valueC11y: {
        value: ["Company", "streaming"],
        certainty: 0.8
    }
}
```

or 

```graphql
where:{
    operator:Explore
    path:["name"]
    value: ["Company", "streaming"],
    certainty: 0.8
}
```

**Comment by etiennedi** [comment]
I like the idea and I think this would be a helpful feature to add as part of MVP2.

Out of the suggestions I like the second example much better, as `valueC11y` doesn't read very nicely. Minor proposal, since `value` takes an array, it should be called `values`. Additionally, all the other `value` fields are suffixed with the type, I think we should also keep this up here. So I'd propose something like:

```gql
where:{
    operator:Explore
    path:["name"]
    valuesString: ["Company", "streaming"],
    certainty: 0.8
}
```

To limit the complexity from exploding I'd suggest that at first this only works on paths of the local class, not on cross-refs. I.e. it would work on `path: ["name"]`, but not `path: ["inCountry", "Country", "name"]`. If we do indeed need this, we can come up with a solution to tackle this later, but at the moment this seems quite costly to implement with questionable benefit.

**Comment by bobvanluijt** [comment]
Agreed regarding planning.

For the UX, maybe @laura-ham has some ideas?
