### ISSUE TITLE
Discussion: take crefs in consideration while creating the centroid

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#899]
## Discussion point

Currently, the c11y-centroid is _only_ created based on the available string objects. (For example, a class City with the reference `inCountry` does not take the country into account.)

I suggest to;
1. Go `n`-deep per concept. Or;
2. Allow a user to specify this in their search.

## Risk

I don't know what the impact will be on the generated vector, it could become generic and loose contextual value.

**Comment by etiennedi** [comment]
Out of the two suggestions, I see only one as viable:

> Go n-deep per concept. Or;

This is viable to me, the only thing to be careful of is the additional time it takes to index, since we now have to essentially do a read before write operation. These are very slow with our current NoSQL stack. Especially with n > 1 they'll esentially have O(n^2) complexity. So it's only viable to
1. only run them on regular imports, not on batch imports
2. run them completely async, i.e. as a Spark Job. This is in my opinion the cleaner option, but also more costly to implement.

> Allow a user to specify this in their search.
Not sure how this would solve the problem as we have to create exactly one item in the index at index time. At search time, we won't know why a centroid is a certain way (i.e. whether it's moved a bit in the direction of Country because of the `inCountry` reference, etc). All we do when searching is build a centroid of the search term and look for the closest match.

**Comment by bobvanluijt** [comment]
Is there any way to validate this first? This is (another) hypothetical assumption. For some case going n=0 deep should be enough.

**Comment by etiennedi** [comment]
95% of this is already validated. The reason the batch importer is faster than the regular importer is because it doesn't do any reads before writing. This is also why importing concepts and importing crefs in batch is a two-step process. 

So, we already know (not just an assumption, we can clearly see that non-batch import is orders of magnitude slower than batch and it is to be expected with NoSQL tech) that we have to avoid reads at bulk write time. 

The questions we need to answer are in my opinion:

1. How important of a feature is vector search, i.e. which percentages of use cases will need it?
1. If the answer to 1 is close to 100%, we need a solution that supports batch importing (most likely an async indexing strategy)
1. If the answer to 1 is close to 0%, we could could accept that if vector search is desired that batch importing is not possible. This would however mean that very large graphs (billions of nodes) won't support vector search, as they are impossible to import without batching

For the async option I could also see a hybrid approach:
1. During batch import time (concepts only) we build a centroid based only on the class itself (cheap, because we don't need to fire off read queries). As a result, a vector index (albeit not an ideal one) is immediately available
2. During batch importing of references we don't update the centroids at this would break batch functionality
3. As soon as all imports are done, we start an async reindex process that will also resolve all cross-refs. How deep we want to go could be a config option on the schema or a global option to always go n levels deep. Whether this is done with Spark or something else is up for debate, the important thing is that it's an async background job.

The big upside is that we need an async reindex job anyway if we want to support contextionary upgrades. going from 0.x.0 to 0.(x+1).0 all vector positions don't make sense anymore and need to be recreated.
